export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  content: string;
}

const shopifyPost: Post = {
  slug: "shopify-meta-tags-complete-guide",
  title: "Shopify Meta Tags: The Complete Fix Guide (2026)",
  description:
    "Most Shopify stores have broken or missing meta tags costing them Google rankings. Here's every issue, why it matters, and exactly how to fix it.",
  date: "2026-03-18",
  readTime: "8 min read",
  content: [
    "## Why Shopify meta tags are silently killing your rankings",
    "",
    "Shopify auto-generates meta tags for your store. That sounds helpful until you realise what it actually generates: generic title tags copied from product names, meta descriptions that repeat the title, and Open Graph images that default to your first product photo.",
    "",
    "Google looks at meta tags to understand what your page is about and decide where to rank it. If your meta tags are wrong, generic, or missing — you're invisible.",
    "",
    "Here's what we found when we audited 20 random Shopify stores:",
    "",
    "- **85%** had title tags over 60 characters (Google truncates these in search results)",
    "- **70%** had missing or incorrect Open Graph images (ugly previews when shared on social media)",
    "- **40%** had meta descriptions that were auto-generated or blank",
    "- **90%** had no structured data (schema markup)",
    "",
    "These aren't cosmetic problems. Each one costs you rankings and clicks.",
    "",
    "---",
    "",
    "## The 5 most common Shopify meta tag problems",
    "",
    "### 1. Title tags that are too long",
    "",
    "Google displays approximately 60 characters of your title tag in search results. Shopify's default format is usually: **[Product Name] – [Shop Name]**",
    "",
    "If your product name is 'Organic Cotton Premium Heavyweight T-Shirt in Navy Blue' and your shop is 'The Great T-Shirt Company', your title tag is 80+ characters — and Google will cut it off mid-sentence.",
    "",
    "**The fix:** Rewrite title tags to under 60 characters. Lead with the most important keyword. Add your brand at the end if space allows.",
    "",
    "Good: Navy Organic Cotton T-Shirt | The Great T-Shirt Co",
    "",
    "### 2. Meta descriptions that are duplicated or missing",
    "",
    "Shopify often uses the same meta description template across hundreds of product pages. Google penalises duplicate content and will often ignore duplicated meta descriptions entirely — writing its own version using random text from your page.",
    "",
    "**The fix:** Write a unique 150-160 character meta description for every key page. Include the primary keyword and a clear value proposition. Include a soft call to action.",
    "",
    "Good: Shop our bestselling navy organic cotton t-shirt. Heavyweight 280gsm, sustainably sourced. Free delivery over £50. 4.9 stars from 2,400 reviews.",
    "",
    "### 3. Open Graph tags not set for product pages",
    "",
    "Open Graph tags control how your pages look when shared on Facebook, LinkedIn, Twitter, or in iMessage previews. If og:image isn't set, the platform will either grab a random image from your page or show a blank preview.",
    "",
    "A bad social preview kills click-through rates. People scroll past broken-looking links.",
    "",
    "**The fix:** Set og:title, og:description, og:image, and og:type for every page. The og:image should be at least 1200×630px. Shopify themes often have a field for this in the theme settings.",
    "",
    "### 4. Missing canonical tags",
    "",
    "If your product appears at multiple URLs (e.g., from different collection paths), Google sees these as duplicate pages and may penalise both. Canonical tags tell Google which URL is the 'real' version.",
    "",
    "**The fix:** Ensure every page has a canonical tag pointing to its primary URL. In Shopify, this is usually handled automatically — but check it's working correctly.",
    "",
    "### 5. No structured data (schema markup)",
    "",
    "Structured data tells Google exactly what your page contains: a product, a price, a review, an event. It unlocks rich results — star ratings, price ranges, availability displayed directly in search results.",
    "",
    "Rich results get significantly more clicks than plain results.",
    "",
    "**The fix:** Add JSON-LD structured data to your product pages. For Shopify stores, you need at minimum: Product schema with name, description, image, offers (with price and availability), and aggregateRating.",
    "",
    "---",
    "",
    "## How to audit your Shopify meta tags (free)",
    "",
    "The fastest way is to use [GetMetaFix](https://getmetafix.com) — paste in your Shopify store URL and get a full audit in 30 seconds. It checks all the issues above, scores them by severity, and shows you exactly what's wrong.",
    "",
    "No account required, free to audit.",
    "",
    "If you want the AI-generated fixes (exact HTML snippets to copy-paste), that's $29 one-time.",
    "",
    "---",
    "",
    "## Shopify SEO meta tags checklist",
    "",
    "Use this before launching any new page or product:",
    "",
    "- [ ] Title tag under 60 characters with primary keyword",
    "- [ ] Meta description 150-160 characters, unique, includes keyword + CTA",
    "- [ ] og:title set",
    "- [ ] og:description set",
    "- [ ] og:image set (1200×630px minimum)",
    "- [ ] og:type set (usually website for homepage, product for products)",
    "- [ ] twitter:card set (usually summary_large_image)",
    "- [ ] Canonical URL pointing to primary URL",
    "- [ ] JSON-LD product schema on product pages",
    "",
    "Run a free audit at [getmetafix.com](https://getmetafix.com) to check all of these automatically.",
  ].join("\n"),
};

const ogPost: Post = {
  slug: "open-graph-tags-missing-fix",
  title: "Open Graph Tags Missing? Here's Exactly How to Fix Them",
  description:
    "Missing og:image and og:title mean broken social previews every time someone shares your page. Fix it in 10 minutes with this step-by-step guide.",
  date: "2026-03-18",
  readTime: "6 min read",
  content: [
    "## What Open Graph tags are and why missing ones cost you traffic",
    "",
    "Every time someone shares your website on social media — Facebook, LinkedIn, Twitter, iMessage, Slack — those platforms read your Open Graph (OG) tags to build the preview card.",
    "",
    "Your OG tags determine:",
    "- The **title** shown in the preview",
    "- The **description** below it",
    "- The **image** displayed",
    "- The **URL** shown",
    "",
    "If these tags are missing or wrong, you get a broken preview: wrong title, wrong image (or none), wrong description. People scroll past. Clicks die.",
    "",
    "We've audited thousands of pages. **70% have at least one broken or missing OG tag.** Most owners have no idea.",
    "",
    "---",
    "",
    "## The 5 Open Graph tags you need on every page",
    "",
    "### 1. og:title",
    "",
    "The headline shown in social previews. Should match your page title (or be slightly rewritten for social). Keep it under 60 characters.",
    "",
    "HTML: meta property='og:title' content='Your Page Title Here'",
    "",
    "### 2. og:description",
    "",
    "2-3 sentences shown below the title in the preview. Expand on the title, add a hook. Keep it under 160 characters.",
    "",
    "### 3. og:image",
    "",
    "The single most important OG tag. A compelling image dramatically increases click-through on social shares.",
    "",
    "**Requirements:**",
    "- Minimum 1200×630px (1.91:1 ratio)",
    "- Under 8MB",
    "- JPG or PNG",
    "- Absolute URL (not relative)",
    "- The image must actually exist at that URL",
    "",
    "### 4. og:url",
    "",
    "The canonical URL of your page. Prevents duplicate content issues when the same page is shared from different URLs.",
    "",
    "### 5. og:type",
    "",
    "Tells platforms what kind of content this is. For most pages, it's 'website'. For articles, use 'article'. For products, use 'product'.",
    "",
    "---",
    "",
    "## How to add OG tags to different platforms",
    "",
    "### WordPress (with Yoast SEO)",
    "",
    "- Install Yoast SEO if you haven't already",
    "- Go to each page/post → Yoast SEO → Social tab",
    "- Set the Social title, description, and image",
    "- Alternatively: go to SEO → Social → Facebook → enable 'Add Open Graph meta data'",
    "",
    "Yoast auto-generates OG tags from your SEO title/description. But you should set a custom OG image for important pages.",
    "",
    "### Shopify",
    "",
    "- Go to Online Store → Preferences → scroll to Social sharing image",
    "- Upload a 1200×630px image for the homepage",
    "- For product pages: go to each product → scroll to 'Search engine listing preview' → edit title + description",
    "- Note: Shopify doesn't have native per-page OG image fields — use a theme that supports it or add to your theme's head template",
    "",
    "### Webflow",
    "",
    "- Open the page settings for each page (gear icon)",
    "- Scroll to 'Open Graph Settings'",
    "- Set title, description, and upload an image",
    "- Publish",
    "",
    "### Next.js (App Router)",
    "",
    "In Next.js 13+ with App Router, use the metadata export in your page.tsx:",
    "",
    "export const metadata = { openGraph: { title: 'Page Title', description: 'Page description', images: [{ url: 'https://yoursite.com/og.jpg', width: 1200, height: 630 }] } }",
    "",
    "---",
    "",
    "## How to test your Open Graph tags",
    "",
    "After adding or updating OG tags, test them before sharing:",
    "",
    "- **Facebook Sharing Debugger**: [developers.facebook.com/tools/debug](https://developers.facebook.com/tools/debug) — paste your URL, see exactly how Facebook will render it. Use 'Scrape Again' to clear the cache.",
    "- **Twitter Card Validator**: [cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)",
    "- **LinkedIn Post Inspector**: [linkedin.com/post-inspector](https://www.linkedin.com/post-inspector/)",
    "- **GetMetaFix** (free): [getmetafix.com](https://getmetafix.com) — checks all OG tags in one audit, tells you what's missing and what's wrong.",
    "",
    "---",
    "",
    "## The most common OG image mistakes",
    "",
    "**1. Relative URLs**",
    "'/images/og.jpg' won't work. Must be 'https://yoursite.com/images/og.jpg'.",
    "",
    "**2. Image doesn't exist**",
    "The URL is set but the file isn't there. Facebook will show nothing.",
    "",
    "**3. Wrong dimensions**",
    "Images smaller than 600×315px may not display. Use 1200×630px for best results across all platforms.",
    "",
    "**4. Same image on every page**",
    "Your homepage's OG image on a blog post looks lazy and confuses people. Use relevant images per page.",
    "",
    "**5. Image has text that gets cut off**",
    "Facebook/LinkedIn crop differently on mobile vs desktop. Keep important text in the centre 80% of the image.",
    "",
    "---",
    "",
    "## Fix your OG tags in 10 minutes",
    "",
    "- Run a free audit at [getmetafix.com](https://getmetafix.com) — see exactly which OG tags are missing",
    "- Create a 1200×630px branded image (Canva has free templates)",
    "- Add the 5 tags above to your HTML head",
    "- Test in Facebook Debugger",
    "- Done",
    "",
    "The $29 fix package at GetMetaFix generates the exact HTML you need, tailored to your page's content.",
  ].join("\n"),
};

const seoAuditPost: Post = {
  slug: "free-seo-audit-tool-complete-guide",
  title: "Free SEO Audit Tool: Find and Fix Every Issue in 30 Seconds (2026)",
  description:
    "Most free SEO audit tools tell you what's wrong but not how to fix it. Here's how to run a real SEO audit, what to look for, and how to fix issues fast.",
  date: "2026-03-19",
  readTime: "7 min read",
  content: [
    "## Why most SEO audits don't lead to results",
    "",
    "Free SEO audit tools are everywhere. Google Search Console, Screaming Frog, Ahrefs — they'll all generate a long list of issues, colour-coded by severity, with vague labels like 'missing meta description' and 'H1 tag not found.'",
    "",
    "The problem isn't finding the issues. It's knowing which ones actually matter, in what order to fix them, and what the fixed version should look like.",
    "",
    "We've spoken to dozens of site owners who ran free audits, got a report with 47 issues, and then did nothing — because the report told them what was broken but not what to do about it.",
    "",
    "This guide is different. Here's how to run an SEO audit that leads to actual improvements.",
    "",
    "---",
    "",
    "## The 5 SEO categories that matter most",
    "",
    "A real SEO audit covers five areas. Here's what each one means and why it matters.",
    "",
    "### 1. Meta tags",
    "",
    "Meta tags are HTML elements in your page's `<head>` that describe the page to search engines and social platforms. The critical ones:",
    "",
    "- **Title tag**: The blue link text in Google search results. Should be 50-60 characters, include your primary keyword, and be unique per page.",
    "- **Meta description**: The two lines of text below the title in search results. 150-160 characters. Won't directly affect rankings but affects click-through rate.",
    "- **Canonical tag**: Tells Google which URL is the 'real' version of a page — prevents duplicate content issues.",
    "",
    "**Most common problems:** Title tags over 60 characters (gets truncated), missing or duplicated descriptions, no canonical tags on paginated content.",
    "",
    "### 2. Open Graph tags",
    "",
    "Open Graph (OG) tags control how your pages look when shared on Facebook, LinkedIn, Slack, and iMessage. Missing or wrong OG tags mean broken-looking link previews — which kills click-through on social shares.",
    "",
    "The essential OG tags: `og:title`, `og:description`, `og:image` (minimum 1200×630px), `og:url`, `og:type`.",
    "",
    "**Most common problem:** Missing `og:image` or using a relative URL that doesn't resolve.",
    "",
    "### 3. Twitter Cards",
    "",
    "Twitter has its own meta tag system. The key tag is `twitter:card` — set it to `summary_large_image` to show a large image preview when links are shared on X/Twitter.",
    "",
    "Without this, shared links show a tiny thumbnail or no image at all.",
    "",
    "### 4. Heading structure",
    "",
    "Your page should have exactly one `<h1>` tag (the main topic), followed by `<h2>` and `<h3>` subheadings in logical order. Multiple H1s or missing H1s are among the most common (and easiest to fix) SEO issues.",
    "",
    "### 5. Image alt text",
    "",
    "Every image should have an `alt` attribute describing what it shows. This helps Google understand images and is essential for accessibility. Images without alt text are invisible to search engines.",
    "",
    "---",
    "",
    "## How to run a free SEO audit in 30 seconds",
    "",
    "The fastest way: paste any URL into [GetMetaFix](https://getmetafix.com). It audits all 12 critical checks across the 5 categories above and returns a prioritised list of issues with severity scores.",
    "",
    "No account required. Free for the full audit.",
    "",
    "What you get:",
    "- ✅ Pass/fail on every check",
    "- Severity score (critical, warning, info)",
    "- What each issue means in plain English",
    "- The $29 Fix Package adds AI-generated code snippets: the exact HTML to add to your page to fix each issue",
    "",
    "---",
    "",
    "## SEO audit checklist (12 checks)",
    "",
    "Run through this for any page you want to rank:",
    "",
    "**Meta tags**",
    "- [ ] Title tag present",
    "- [ ] Title tag under 60 characters",
    "- [ ] Meta description present",
    "- [ ] Meta description under 160 characters",
    "- [ ] Canonical URL set",
    "",
    "**Open Graph**",
    "- [ ] og:title set",
    "- [ ] og:description set",
    "- [ ] og:image set with absolute URL",
    "- [ ] og:image is at least 1200×630px",
    "",
    "**Twitter Cards**",
    "- [ ] twitter:card set",
    "",
    "**Page structure**",
    "- [ ] Exactly one H1 tag",
    "- [ ] All images have alt text",
    "",
    "---",
    "",
    "## What to fix first",
    "",
    "When you get a list of SEO issues, prioritise in this order:",
    "",
    "**1. Missing title tags** — This is the highest-impact fix. Without a title tag, Google writes its own, usually badly.",
    "",
    "**2. Missing canonical tags** — If you have duplicate content (product pages at multiple URLs, paginated content), this is causing silent damage.",
    "",
    "**3. Missing og:image** — Every time someone shares your link on social media and gets a blank preview, you're losing clicks. Fix this fast.",
    "",
    "**4. Title tags over 60 characters** — Gets truncated in search results. Rewrite to put the keyword first.",
    "",
    "**5. Missing alt text** — Affects both SEO and accessibility. Usually quick to fix.",
    "",
    "---",
    "",
    "## How often should you audit?",
    "",
    "At minimum: before launching any new page, after major site redesigns, and once a month for active sites.",
    "",
    "The real problem is that SEO issues accumulate invisibly. A developer pushes a change that accidentally removes canonical tags. A theme update wipes custom meta tags. An image upload breaks an OG image URL.",
    "",
    "You don't find out until rankings drop — weeks later.",
    "",
    "That's why [GetMetaFix](https://getmetafix.com) offers weekly monitoring at $19/month: it audits your site every week and emails you when something breaks. Most issues get caught and fixed within 24 hours instead of being silently costing you traffic for months.",
    "",
    "---",
    "",
    "## The bottom line",
    "",
    "Run the free audit at [getmetafix.com](https://getmetafix.com). Fix the critical issues first. Set up weekly monitoring so problems don't sneak back.",
    "",
    "SEO isn't complicated. Most of the wins are just fixing basic errors that most sites have and most owners don't know about.",
  ].join("\n"),
};

const metaDescPost: Post = {
  slug: "meta-description-not-showing-google",
  title: "Meta Description Not Showing in Google? Here's Why (and How to Fix It)",
  description:
    "Google is ignoring your meta description and writing its own? Here's every reason why it happens and exactly how to fix it — for WordPress, Shopify, and any site.",
  date: "2026-03-19",
  readTime: "6 min read",
  content: [
    "## Why Google isn't showing your meta description",
    "",
    "You carefully wrote a meta description. You saved it. You checked the HTML — it's there. But in Google search results, the snippet under your page title says something completely different.",
    "",
    "You're not imagining it. Google ignores meta descriptions roughly **70% of the time** according to research by Portent — rewriting them based on the page content instead.",
    "",
    "The good news: this usually happens for specific, fixable reasons. Here's every one of them.",
    "",
    "---",
    "",
    "## 7 reasons Google ignores your meta description",
    "",
    "### 1. Your meta description doesn't match the search query",
    "",
    "Google rewrites snippets to match what the user searched for. If someone searches 'how to fix Shopify title tags' and your meta description talks about 'our complete SEO services', Google will pull a more relevant sentence from your page body instead.",
    "",
    "**The fix:** Write meta descriptions that directly answer the most likely search queries for that page. Include the primary keyword naturally.",
    "",
    "### 2. Your meta description is too long",
    "",
    "Google shows approximately 155-160 characters of a meta description. If yours is longer, Google may truncate it awkwardly — or decide the whole thing is poorly written and replace it.",
    "",
    "**The fix:** Keep meta descriptions between 120-155 characters. End with a complete thought, not mid-sentence.",
    "",
    "### 3. Your meta description is too short or too vague",
    "",
    "A meta description that says 'Buy shoes online' doesn't give Google enough to work with. It'll pull a more descriptive sentence from elsewhere on your page.",
    "",
    "**The fix:** Write 2-3 sentences. Describe specifically what the page contains, for whom, and what value they'll get.",
    "",
    "### 4. Your meta description is duplicate",
    "",
    "If you're using the same meta description on multiple pages, Google knows it's a template and will ignore it in favour of page-specific content.",
    "",
    "This is extremely common on Shopify and WordPress sites where the theme auto-generates descriptions from a single template.",
    "",
    "**The fix:** Write unique meta descriptions for every important page. At minimum: homepage, product/service pages, blog posts.",
    "",
    "### 5. The meta description tag is missing or malformed",
    "",
    "Sometimes the tag simply isn't there — or it's present but has a typo in the attribute name. Check your page source (Ctrl+U or Cmd+U) and search for `meta name=\"description\"`.",
    "",
    "Common mistakes:",
    "- `name='descriptions'` (typo — extra s)",
    "- `meta description=\"...\"` (missing the name attribute)",
    "- The tag is commented out `<!-- <meta name=\"description\"...> -->`",
    "",
    "**The fix:** Run a free audit at [getmetafix.com](https://getmetafix.com) to detect this instantly. It checks whether the tag is present and correctly formatted.",
    "",
    "### 6. The meta description is placed outside the `<head>` tag",
    "",
    "Google only reads meta tags inside `<head>`. If a CMS or theme bug placed your description tag in the `<body>`, Google won't see it.",
    "",
    "**The fix:** View page source, check that `<meta name=\"description\">` appears before `</head>`.",
    "",
    "### 7. Your page hasn't been re-crawled since you updated the description",
    "",
    "If you recently fixed your meta description, Google may not have re-crawled the page yet. It can take days to weeks for changes to appear in search results.",
    "",
    "**The fix:** Go to Google Search Console → URL Inspection → enter your URL → click 'Request Indexing'. This tells Google to re-crawl sooner.",
    "",
    "---",
    "",
    "## Does it matter if Google rewrites your meta description?",
    "",
    "Partly. Here's the honest answer:",
    "",
    "**Meta descriptions don't directly affect rankings.** Google confirmed this. The content of your meta description won't make you rank higher or lower.",
    "",
    "**But meta descriptions affect click-through rate** — and that does matter.",
    "",
    "A well-written meta description that matches what a searcher is looking for gets more clicks. More clicks = more traffic. More traffic = positive signal to Google. It compounds over time.",
    "",
    "A meta description Google rewrites might be fine — or it might pull an awkward, context-free sentence from your page that makes people skip your result.",
    "",
    "You can't control what Google shows, but you can write meta descriptions so compelling and well-matched to search intent that Google uses them anyway.",
    "",
    "---",
    "",
    "## How to write meta descriptions Google actually uses",
    "",
    "The formula that works:",
    "",
    "**[Primary keyword] + [specific value proposition] + [soft CTA] = 150 chars**",
    "",
    "Examples:",
    "",
    "✅ Good: *'Shopify meta tag audit in 30 seconds. See exactly what's broken — title tags, Open Graph, canonical URLs. Free, no signup. Fix issues for $29.'*",
    "",
    "❌ Bad: *'We help businesses improve their SEO and get more traffic from Google.'*",
    "",
    "The good version is specific, answers a question, and has a CTA. The bad version is generic and could apply to any business.",
    "",
    "---",
    "",
    "## Check your meta descriptions in 30 seconds",
    "",
    "Run any URL through [getmetafix.com](https://getmetafix.com) — it checks whether your meta description is present, correctly formatted, the right length, and unique.",
    "",
    "If it's missing or wrong, the $29 Fix Package generates a rewritten meta description for your page — tailored to your content and keyword.",
  ].join("\n"),
};

const wordpressMetaPost: Post = {
  slug: "wordpress-meta-tags-guide",
  title: "WordPress Meta Tags: The Complete Setup Guide (No Plugin Needed)",
  description:
    "Yoast and Rank Math are popular, but do you actually need them? This guide covers how to add meta tags to WordPress correctly — with or without a plugin.",
  date: "2026-03-19",
  readTime: "8 min read",
  content: [
    "## WordPress meta tags: what most guides get wrong",
    "",
    "Most WordPress SEO guides tell you to install Yoast SEO and call it done. That's reasonable advice. But it skips the most important part: understanding what meta tags actually do, which ones matter, and how to verify they're working.",
    "",
    "We've audited hundreds of WordPress sites that had Yoast installed — and still had critical meta tag failures. Plugin doesn't mean working.",
    "",
    "This guide covers everything: what WordPress meta tags you need, how to add them (with and without plugins), and how to audit them.",
    "",
    "---",
    "",
    "## The 3 types of meta tags WordPress sites need",
    "",
    "### 1. SEO meta tags",
    "",
    "These go in your `<head>` and tell Google what each page is about:",
    "",
    "- **Title tag** (`<title>`): The blue headline in Google results. 50-60 characters. Include your primary keyword.",
    "- **Meta description** (`<meta name=\"description\">`): The snippet below the title. 150-160 characters. Affects click-through rate.",
    "- **Canonical tag** (`<link rel=\"canonical\">`): The 'official' URL for this page — prevents duplicate content penalties.",
    "- **Robots tag** (`<meta name=\"robots\">`): Tells Google whether to index the page. Default is 'index, follow' — only add this if you need to change that.",
    "",
    "### 2. Open Graph tags",
    "",
    "These control how your pages look when shared on Facebook, LinkedIn, iMessage, and Slack:",
    "",
    "- `og:title` — The headline in the preview card",
    "- `og:description` — The description below",
    "- `og:image` — The preview image (minimum 1200×630px, absolute URL)",
    "- `og:url` — Your page's canonical URL",
    "- `og:type` — Content type: 'website', 'article', or 'product'",
    "",
    "Missing these = ugly link previews when anyone shares your content. More common than you'd think.",
    "",
    "### 3. Twitter Card tags",
    "",
    "X/Twitter uses its own tag system:",
    "",
    "- `twitter:card` — Set to `summary_large_image` for a big image preview",
    "- `twitter:title` and `twitter:description` — Often inherited from OG tags",
    "- `twitter:image` — The image (can be same as og:image)",
    "",
    "---",
    "",
    "## Option 1: Add meta tags with Yoast SEO (recommended for most sites)",
    "",
    "Yoast SEO is the most-used WordPress SEO plugin. Here's how to use it correctly:",
    "",
    "**Setup:**",
    "1. Install and activate Yoast SEO (free version is fine for most sites)",
    "2. Go to SEO → General → Features → enable 'Advanced settings pages'",
    "3. Go to SEO → Social → Facebook → enable 'Add Open Graph meta data'",
    "4. Go to SEO → Social → Twitter → enable Twitter card",
    "",
    "**Per-page setup:**",
    "For each page/post, scroll to the Yoast SEO panel below the editor.",
    "- SEO tab: Set 'SEO title' (what appears in Google) and 'Meta description'",
    "- Social tab: Set Facebook and Twitter title/description/image",
    "",
    "**Common Yoast mistake:** Using the 'focus keyphrase' as your title. The title goes in 'SEO title' — they're separate fields.",
    "",
    "**Run a free audit to verify Yoast is working correctly:** [getmetafix.com](https://getmetafix.com) — paste your URL and see exactly what tags Yoast generated.",
    "",
    "---",
    "",
    "## Option 2: Add meta tags with Rank Math",
    "",
    "Rank Math is a newer plugin that includes more features in the free tier than Yoast. Setup is similar:",
    "",
    "1. Install Rank Math → run the setup wizard",
    "2. During setup, enable 'Social Meta' when prompted",
    "3. Go to Rank Math → Titles & Meta → set global defaults",
    "4. Per page: use the Rank Math panel below the editor → Edit Snippet → fill in title and description",
    "",
    "Rank Math auto-generates OG tags from your SEO title/description. But set per-page OG images manually for important pages.",
    "",
    "---",
    "",
    "## Option 3: Add meta tags without a plugin",
    "",
    "If you're comfortable editing theme files, you can add meta tags directly. This is the cleanest approach but requires care — a mistake can break the whole site.",
    "",
    "Add to your theme's `functions.php` or a child theme:",
    "",
    "```php",
    "function custom_meta_tags() {",
    "  if ( is_singular() ) {",
    "    global $post;",
    "    $description = get_the_excerpt( $post );",
    "    $image = get_the_post_thumbnail_url( $post, 'large' );",
    "    echo '<meta name=\"description\" content=\"' . esc_attr( $description ) . '\">';",
    "    echo '<meta property=\"og:title\" content=\"' . esc_attr( get_the_title() ) . '\">';",
    "    echo '<meta property=\"og:description\" content=\"' . esc_attr( $description ) . '\">';",
    "    echo '<meta property=\"og:image\" content=\"' . esc_url( $image ) . '\">';",
    "    echo '<meta property=\"og:url\" content=\"' . esc_url( get_permalink() ) . '\">';",
    "    echo '<meta property=\"og:type\" content=\"article\">';",
    "    echo '<meta name=\"twitter:card\" content=\"summary_large_image\">';",
    "  }",
    "}",
    "add_action( 'wp_head', 'custom_meta_tags' );",
    "```",
    "",
    "This is a basic version. For production, you'd want per-page custom fields for more control.",
    "",
    "---",
    "",
    "## The meta tags most WordPress sites are missing",
    "",
    "Even with Yoast installed, we see these failures constantly:",
    "",
    "**1. OG image not set on inner pages**",
    "Yoast only auto-sets the OG image on the homepage. Blog posts and product pages often have no og:image — meaning social shares show a broken preview.",
    "",
    "**Fix:** Set a featured image on every post. Yoast uses the featured image as the OG image automatically.",
    "",
    "**2. Meta description auto-generated**",
    "Yoast will auto-generate a meta description from your content if you don't write one. It's almost always worse than what you'd write. Google often ignores these.",
    "",
    "**Fix:** Write a unique meta description for every important page. 155 characters. Include the keyword.",
    "",
    "**3. Title tag includes site name on short pages**",
    "Yoast's default title format is usually: `Post Title - Site Name`. If your post title is short, this is fine. If it's long (45+ chars), appending ' - Site Name' pushes it over 60 characters.",
    "",
    "**Fix:** Change the title separator to a shorter format, or shorten your post titles to leave room.",
    "",
    "**4. Canonical tag pointing to wrong URL**",
    "On paginated archives or when the same post appears under multiple categories, canonical tags can point to unexpected URLs. This dilutes your ranking power.",
    "",
    "**Fix:** Check canonical tags with [getmetafix.com](https://getmetafix.com) — it shows you exactly which canonical URL your page is reporting.",
    "",
    "---",
    "",
    "## How to audit your WordPress meta tags",
    "",
    "The fastest way: paste any page URL into [getmetafix.com](https://getmetafix.com). It checks all 12 critical meta tag elements in 30 seconds and shows you exactly what Yoast (or your custom setup) is outputting.",
    "",
    "More thorough check: View source (`Cmd+U` / `Ctrl+U`) and search for `<meta name=\"description\"` and `<meta property=\"og:image\"`. If they're missing, you know what to fix.",
    "",
    "The $29 Fix Package at GetMetaFix generates the exact meta tag HTML tailored to your page — paste it in, or give it to your developer.",
  ].join("\n"),
};

export const posts: Post[] = [shopifyPost, ogPost, seoAuditPost, metaDescPost, wordpressMetaPost];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
