export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  content: string;
}

const shopifyPost: Post = {
  slug: "shopify-meta-tags-complete-guide",
  title: "Shopify Meta Tags: The Complete Fix Guide (2026)",
  description:
    "Most Shopify stores have broken or missing meta tags costing them Google rankings. Here's every issue, why it matters, and exactly how to fix it.",
  date: "2026-03-18",
  readTime: "8 min read",
  content: [
    "## Why Shopify meta tags are silently killing your rankings",
    "",
    "Shopify auto-generates meta tags for your store. That sounds helpful until you realise what it actually generates: generic title tags copied from product names, meta descriptions that repeat the title, and Open Graph images that default to your first product photo.",
    "",
    "Google looks at meta tags to understand what your page is about and decide where to rank it. If your meta tags are wrong, generic, or missing — you're invisible.",
    "",
    "Here's what we found when we audited 20 random Shopify stores:",
    "",
    "- **85%** had title tags over 60 characters (Google truncates these in search results)",
    "- **70%** had missing or incorrect Open Graph images (ugly previews when shared on social media)",
    "- **40%** had meta descriptions that were auto-generated or blank",
    "- **90%** had no structured data (schema markup)",
    "",
    "These aren't cosmetic problems. Each one costs you rankings and clicks.",
    "",
    "---",
    "",
    "## The 5 most common Shopify meta tag problems",
    "",
    "### 1. Title tags that are too long",
    "",
    "Google displays approximately 60 characters of your title tag in search results. Shopify's default format is usually: **[Product Name] – [Shop Name]**",
    "",
    "If your product name is 'Organic Cotton Premium Heavyweight T-Shirt in Navy Blue' and your shop is 'The Great T-Shirt Company', your title tag is 80+ characters — and Google will cut it off mid-sentence.",
    "",
    "**The fix:** Rewrite title tags to under 60 characters. Lead with the most important keyword. Add your brand at the end if space allows.",
    "",
    "Good: Navy Organic Cotton T-Shirt | The Great T-Shirt Co",
    "",
    "### 2. Meta descriptions that are duplicated or missing",
    "",
    "Shopify often uses the same meta description template across hundreds of product pages. Google penalises duplicate content and will often ignore duplicated meta descriptions entirely — writing its own version using random text from your page.",
    "",
    "**The fix:** Write a unique 150-160 character meta description for every key page. Include the primary keyword and a clear value proposition. Include a soft call to action.",
    "",
    "Good: Shop our bestselling navy organic cotton t-shirt. Heavyweight 280gsm, sustainably sourced. Free delivery over £50. 4.9 stars from 2,400 reviews.",
    "",
    "### 3. Open Graph tags not set for product pages",
    "",
    "Open Graph tags control how your pages look when shared on Facebook, LinkedIn, Twitter, or in iMessage previews. If og:image isn't set, the platform will either grab a random image from your page or show a blank preview.",
    "",
    "A bad social preview kills click-through rates. People scroll past broken-looking links.",
    "",
    "**The fix:** Set og:title, og:description, og:image, and og:type for every page. The og:image should be at least 1200×630px. Shopify themes often have a field for this in the theme settings.",
    "",
    "### 4. Missing canonical tags",
    "",
    "If your product appears at multiple URLs (e.g., from different collection paths), Google sees these as duplicate pages and may penalise both. Canonical tags tell Google which URL is the 'real' version.",
    "",
    "**The fix:** Ensure every page has a canonical tag pointing to its primary URL. In Shopify, this is usually handled automatically — but check it's working correctly.",
    "",
    "### 5. No structured data (schema markup)",
    "",
    "Structured data tells Google exactly what your page contains: a product, a price, a review, an event. It unlocks rich results — star ratings, price ranges, availability displayed directly in search results.",
    "",
    "Rich results get significantly more clicks than plain results.",
    "",
    "**The fix:** Add JSON-LD structured data to your product pages. For Shopify stores, you need at minimum: Product schema with name, description, image, offers (with price and availability), and aggregateRating.",
    "",
    "---",
    "",
    "## How to audit your Shopify meta tags (free)",
    "",
    "The fastest way is to use [GetMetaFix](https://getmetafix.com) — paste in your Shopify store URL and get a full audit in 30 seconds. It checks all the issues above, scores them by severity, and shows you exactly what's wrong.",
    "",
    "No account required, free to audit.",
    "",
    "If you want the AI-generated fixes (exact HTML snippets to copy-paste), that's $29 one-time.",
    "",
    "---",
    "",
    "## Shopify SEO meta tags checklist",
    "",
    "Use this before launching any new page or product:",
    "",
    "- [ ] Title tag under 60 characters with primary keyword",
    "- [ ] Meta description 150-160 characters, unique, includes keyword + CTA",
    "- [ ] og:title set",
    "- [ ] og:description set",
    "- [ ] og:image set (1200×630px minimum)",
    "- [ ] og:type set (usually website for homepage, product for products)",
    "- [ ] twitter:card set (usually summary_large_image)",
    "- [ ] Canonical URL pointing to primary URL",
    "- [ ] JSON-LD product schema on product pages",
    "",
    "Run a free audit at [getmetafix.com](https://getmetafix.com) to check all of these automatically.",
  ].join("\n"),
};

const ogPost: Post = {
  slug: "open-graph-tags-missing-fix",
  title: "Open Graph Tags Missing? Here's Exactly How to Fix Them",
  description:
    "Missing og:image and og:title mean broken social previews every time someone shares your page. Fix it in 10 minutes with this step-by-step guide.",
  date: "2026-03-18",
  readTime: "6 min read",
  content: [
    "## What Open Graph tags are and why missing ones cost you traffic",
    "",
    "Every time someone shares your website on social media — Facebook, LinkedIn, Twitter, iMessage, Slack — those platforms read your Open Graph (OG) tags to build the preview card.",
    "",
    "Your OG tags determine:",
    "- The **title** shown in the preview",
    "- The **description** below it",
    "- The **image** displayed",
    "- The **URL** shown",
    "",
    "If these tags are missing or wrong, you get a broken preview: wrong title, wrong image (or none), wrong description. People scroll past. Clicks die.",
    "",
    "We've audited thousands of pages. **70% have at least one broken or missing OG tag.** Most owners have no idea.",
    "",
    "---",
    "",
    "## The 5 Open Graph tags you need on every page",
    "",
    "### 1. og:title",
    "",
    "The headline shown in social previews. Should match your page title (or be slightly rewritten for social). Keep it under 60 characters.",
    "",
    "HTML: meta property='og:title' content='Your Page Title Here'",
    "",
    "### 2. og:description",
    "",
    "2-3 sentences shown below the title in the preview. Expand on the title, add a hook. Keep it under 160 characters.",
    "",
    "### 3. og:image",
    "",
    "The single most important OG tag. A compelling image dramatically increases click-through on social shares.",
    "",
    "**Requirements:**",
    "- Minimum 1200×630px (1.91:1 ratio)",
    "- Under 8MB",
    "- JPG or PNG",
    "- Absolute URL (not relative)",
    "- The image must actually exist at that URL",
    "",
    "### 4. og:url",
    "",
    "The canonical URL of your page. Prevents duplicate content issues when the same page is shared from different URLs.",
    "",
    "### 5. og:type",
    "",
    "Tells platforms what kind of content this is. For most pages, it's 'website'. For articles, use 'article'. For products, use 'product'.",
    "",
    "---",
    "",
    "## How to add OG tags to different platforms",
    "",
    "### WordPress (with Yoast SEO)",
    "",
    "- Install Yoast SEO if you haven't already",
    "- Go to each page/post → Yoast SEO → Social tab",
    "- Set the Social title, description, and image",
    "- Alternatively: go to SEO → Social → Facebook → enable 'Add Open Graph meta data'",
    "",
    "Yoast auto-generates OG tags from your SEO title/description. But you should set a custom OG image for important pages.",
    "",
    "### Shopify",
    "",
    "- Go to Online Store → Preferences → scroll to Social sharing image",
    "- Upload a 1200×630px image for the homepage",
    "- For product pages: go to each product → scroll to 'Search engine listing preview' → edit title + description",
    "- Note: Shopify doesn't have native per-page OG image fields — use a theme that supports it or add to your theme's head template",
    "",
    "### Webflow",
    "",
    "- Open the page settings for each page (gear icon)",
    "- Scroll to 'Open Graph Settings'",
    "- Set title, description, and upload an image",
    "- Publish",
    "",
    "### Next.js (App Router)",
    "",
    "In Next.js 13+ with App Router, use the metadata export in your page.tsx:",
    "",
    "export const metadata = { openGraph: { title: 'Page Title', description: 'Page description', images: [{ url: 'https://yoursite.com/og.jpg', width: 1200, height: 630 }] } }",
    "",
    "---",
    "",
    "## How to test your Open Graph tags",
    "",
    "After adding or updating OG tags, test them before sharing:",
    "",
    "- **Facebook Sharing Debugger**: [developers.facebook.com/tools/debug](https://developers.facebook.com/tools/debug) — paste your URL, see exactly how Facebook will render it. Use 'Scrape Again' to clear the cache.",
    "- **Twitter Card Validator**: [cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)",
    "- **LinkedIn Post Inspector**: [linkedin.com/post-inspector](https://www.linkedin.com/post-inspector/)",
    "- **GetMetaFix** (free): [getmetafix.com](https://getmetafix.com) — checks all OG tags in one audit, tells you what's missing and what's wrong.",
    "",
    "---",
    "",
    "## The most common OG image mistakes",
    "",
    "**1. Relative URLs**",
    "'/images/og.jpg' won't work. Must be 'https://yoursite.com/images/og.jpg'.",
    "",
    "**2. Image doesn't exist**",
    "The URL is set but the file isn't there. Facebook will show nothing.",
    "",
    "**3. Wrong dimensions**",
    "Images smaller than 600×315px may not display. Use 1200×630px for best results across all platforms.",
    "",
    "**4. Same image on every page**",
    "Your homepage's OG image on a blog post looks lazy and confuses people. Use relevant images per page.",
    "",
    "**5. Image has text that gets cut off**",
    "Facebook/LinkedIn crop differently on mobile vs desktop. Keep important text in the centre 80% of the image.",
    "",
    "---",
    "",
    "## Fix your OG tags in 10 minutes",
    "",
    "- Run a free audit at [getmetafix.com](https://getmetafix.com) — see exactly which OG tags are missing",
    "- Create a 1200×630px branded image (Canva has free templates)",
    "- Add the 5 tags above to your HTML head",
    "- Test in Facebook Debugger",
    "- Done",
    "",
    "The $29 fix package at GetMetaFix generates the exact HTML you need, tailored to your page's content.",
  ].join("\n"),
};

const seoAuditPost: Post = {
  slug: "free-seo-audit-tool-complete-guide",
  title: "Free SEO Audit Tool: Find and Fix Every Issue in 30 Seconds (2026)",
  description:
    "Most free SEO audit tools tell you what's wrong but not how to fix it. Here's how to run a real SEO audit, what to look for, and how to fix issues fast.",
  date: "2026-03-19",
  readTime: "7 min read",
  content: [
    "## Why most SEO audits don't lead to results",
    "",
    "Free SEO audit tools are everywhere. Google Search Console, Screaming Frog, Ahrefs — they'll all generate a long list of issues, colour-coded by severity, with vague labels like 'missing meta description' and 'H1 tag not found.'",
    "",
    "The problem isn't finding the issues. It's knowing which ones actually matter, in what order to fix them, and what the fixed version should look like.",
    "",
    "We've spoken to dozens of site owners who ran free audits, got a report with 47 issues, and then did nothing — because the report told them what was broken but not what to do about it.",
    "",
    "This guide is different. Here's how to run an SEO audit that leads to actual improvements.",
    "",
    "---",
    "",
    "## The 5 SEO categories that matter most",
    "",
    "A real SEO audit covers five areas. Here's what each one means and why it matters.",
    "",
    "### 1. Meta tags",
    "",
    "Meta tags are HTML elements in your page's `<head>` that describe the page to search engines and social platforms. The critical ones:",
    "",
    "- **Title tag**: The blue link text in Google search results. Should be 50-60 characters, include your primary keyword, and be unique per page.",
    "- **Meta description**: The two lines of text below the title in search results. 150-160 characters. Won't directly affect rankings but affects click-through rate.",
    "- **Canonical tag**: Tells Google which URL is the 'real' version of a page — prevents duplicate content issues.",
    "",
    "**Most common problems:** Title tags over 60 characters (gets truncated), missing or duplicated descriptions, no canonical tags on paginated content.",
    "",
    "### 2. Open Graph tags",
    "",
    "Open Graph (OG) tags control how your pages look when shared on Facebook, LinkedIn, Slack, and iMessage. Missing or wrong OG tags mean broken-looking link previews — which kills click-through on social shares.",
    "",
    "The essential OG tags: `og:title`, `og:description`, `og:image` (minimum 1200×630px), `og:url`, `og:type`.",
    "",
    "**Most common problem:** Missing `og:image` or using a relative URL that doesn't resolve.",
    "",
    "### 3. Twitter Cards",
    "",
    "Twitter has its own meta tag system. The key tag is `twitter:card` — set it to `summary_large_image` to show a large image preview when links are shared on X/Twitter.",
    "",
    "Without this, shared links show a tiny thumbnail or no image at all.",
    "",
    "### 4. Heading structure",
    "",
    "Your page should have exactly one `<h1>` tag (the main topic), followed by `<h2>` and `<h3>` subheadings in logical order. Multiple H1s or missing H1s are among the most common (and easiest to fix) SEO issues.",
    "",
    "### 5. Image alt text",
    "",
    "Every image should have an `alt` attribute describing what it shows. This helps Google understand images and is essential for accessibility. Images without alt text are invisible to search engines.",
    "",
    "---",
    "",
    "## How to run a free SEO audit in 30 seconds",
    "",
    "The fastest way: paste any URL into [GetMetaFix](https://getmetafix.com). It audits all 12 critical checks across the 5 categories above and returns a prioritised list of issues with severity scores.",
    "",
    "No account required. Free for the full audit.",
    "",
    "What you get:",
    "- ✅ Pass/fail on every check",
    "- Severity score (critical, warning, info)",
    "- What each issue means in plain English",
    "- The $29 Fix Package adds AI-generated code snippets: the exact HTML to add to your page to fix each issue",
    "",
    "---",
    "",
    "## SEO audit checklist (12 checks)",
    "",
    "Run through this for any page you want to rank:",
    "",
    "**Meta tags**",
    "- [ ] Title tag present",
    "- [ ] Title tag under 60 characters",
    "- [ ] Meta description present",
    "- [ ] Meta description under 160 characters",
    "- [ ] Canonical URL set",
    "",
    "**Open Graph**",
    "- [ ] og:title set",
    "- [ ] og:description set",
    "- [ ] og:image set with absolute URL",
    "- [ ] og:image is at least 1200×630px",
    "",
    "**Twitter Cards**",
    "- [ ] twitter:card set",
    "",
    "**Page structure**",
    "- [ ] Exactly one H1 tag",
    "- [ ] All images have alt text",
    "",
    "---",
    "",
    "## What to fix first",
    "",
    "When you get a list of SEO issues, prioritise in this order:",
    "",
    "**1. Missing title tags** — This is the highest-impact fix. Without a title tag, Google writes its own, usually badly.",
    "",
    "**2. Missing canonical tags** — If you have duplicate content (product pages at multiple URLs, paginated content), this is causing silent damage.",
    "",
    "**3. Missing og:image** — Every time someone shares your link on social media and gets a blank preview, you're losing clicks. Fix this fast.",
    "",
    "**4. Title tags over 60 characters** — Gets truncated in search results. Rewrite to put the keyword first.",
    "",
    "**5. Missing alt text** — Affects both SEO and accessibility. Usually quick to fix.",
    "",
    "---",
    "",
    "## How often should you audit?",
    "",
    "At minimum: before launching any new page, after major site redesigns, and once a month for active sites.",
    "",
    "The real problem is that SEO issues accumulate invisibly. A developer pushes a change that accidentally removes canonical tags. A theme update wipes custom meta tags. An image upload breaks an OG image URL.",
    "",
    "You don't find out until rankings drop — weeks later.",
    "",
    "That's why [GetMetaFix](https://getmetafix.com) offers weekly monitoring at $19/month: it audits your site every week and emails you when something breaks. Most issues get caught and fixed within 24 hours instead of being silently costing you traffic for months.",
    "",
    "---",
    "",
    "## The bottom line",
    "",
    "Run the free audit at [getmetafix.com](https://getmetafix.com). Fix the critical issues first. Set up weekly monitoring so problems don't sneak back.",
    "",
    "SEO isn't complicated. Most of the wins are just fixing basic errors that most sites have and most owners don't know about.",
  ].join("\n"),
};

const metaDescPost: Post = {
  slug: "meta-description-not-showing-google",
  title: "Meta Description Not Showing in Google? Here's Why (and How to Fix It)",
  description:
    "Google is ignoring your meta description and writing its own? Here's every reason why it happens and exactly how to fix it — for WordPress, Shopify, and any site.",
  date: "2026-03-19",
  readTime: "6 min read",
  content: [
    "## Why Google isn't showing your meta description",
    "",
    "You carefully wrote a meta description. You saved it. You checked the HTML — it's there. But in Google search results, the snippet under your page title says something completely different.",
    "",
    "You're not imagining it. Google ignores meta descriptions roughly **70% of the time** according to research by Portent — rewriting them based on the page content instead.",
    "",
    "The good news: this usually happens for specific, fixable reasons. Here's every one of them.",
    "",
    "---",
    "",
    "## 7 reasons Google ignores your meta description",
    "",
    "### 1. Your meta description doesn't match the search query",
    "",
    "Google rewrites snippets to match what the user searched for. If someone searches 'how to fix Shopify title tags' and your meta description talks about 'our complete SEO services', Google will pull a more relevant sentence from your page body instead.",
    "",
    "**The fix:** Write meta descriptions that directly answer the most likely search queries for that page. Include the primary keyword naturally.",
    "",
    "### 2. Your meta description is too long",
    "",
    "Google shows approximately 155-160 characters of a meta description. If yours is longer, Google may truncate it awkwardly — or decide the whole thing is poorly written and replace it.",
    "",
    "**The fix:** Keep meta descriptions between 120-155 characters. End with a complete thought, not mid-sentence.",
    "",
    "### 3. Your meta description is too short or too vague",
    "",
    "A meta description that says 'Buy shoes online' doesn't give Google enough to work with. It'll pull a more descriptive sentence from elsewhere on your page.",
    "",
    "**The fix:** Write 2-3 sentences. Describe specifically what the page contains, for whom, and what value they'll get.",
    "",
    "### 4. Your meta description is duplicate",
    "",
    "If you're using the same meta description on multiple pages, Google knows it's a template and will ignore it in favour of page-specific content.",
    "",
    "This is extremely common on Shopify and WordPress sites where the theme auto-generates descriptions from a single template.",
    "",
    "**The fix:** Write unique meta descriptions for every important page. At minimum: homepage, product/service pages, blog posts.",
    "",
    "### 5. The meta description tag is missing or malformed",
    "",
    "Sometimes the tag simply isn't there — or it's present but has a typo in the attribute name. Check your page source (Ctrl+U or Cmd+U) and search for `meta name=\"description\"`.",
    "",
    "Common mistakes:",
    "- `name='descriptions'` (typo — extra s)",
    "- `meta description=\"...\"` (missing the name attribute)",
    "- The tag is commented out `<!-- <meta name=\"description\"...> -->`",
    "",
    "**The fix:** Run a free audit at [getmetafix.com](https://getmetafix.com) to detect this instantly. It checks whether the tag is present and correctly formatted.",
    "",
    "### 6. The meta description is placed outside the `<head>` tag",
    "",
    "Google only reads meta tags inside `<head>`. If a CMS or theme bug placed your description tag in the `<body>`, Google won't see it.",
    "",
    "**The fix:** View page source, check that `<meta name=\"description\">` appears before `</head>`.",
    "",
    "### 7. Your page hasn't been re-crawled since you updated the description",
    "",
    "If you recently fixed your meta description, Google may not have re-crawled the page yet. It can take days to weeks for changes to appear in search results.",
    "",
    "**The fix:** Go to Google Search Console → URL Inspection → enter your URL → click 'Request Indexing'. This tells Google to re-crawl sooner.",
    "",
    "---",
    "",
    "## Does it matter if Google rewrites your meta description?",
    "",
    "Partly. Here's the honest answer:",
    "",
    "**Meta descriptions don't directly affect rankings.** Google confirmed this. The content of your meta description won't make you rank higher or lower.",
    "",
    "**But meta descriptions affect click-through rate** — and that does matter.",
    "",
    "A well-written meta description that matches what a searcher is looking for gets more clicks. More clicks = more traffic. More traffic = positive signal to Google. It compounds over time.",
    "",
    "A meta description Google rewrites might be fine — or it might pull an awkward, context-free sentence from your page that makes people skip your result.",
    "",
    "You can't control what Google shows, but you can write meta descriptions so compelling and well-matched to search intent that Google uses them anyway.",
    "",
    "---",
    "",
    "## How to write meta descriptions Google actually uses",
    "",
    "The formula that works:",
    "",
    "**[Primary keyword] + [specific value proposition] + [soft CTA] = 150 chars**",
    "",
    "Examples:",
    "",
    "✅ Good: *'Shopify meta tag audit in 30 seconds. See exactly what's broken — title tags, Open Graph, canonical URLs. Free, no signup. Fix issues for $29.'*",
    "",
    "❌ Bad: *'We help businesses improve their SEO and get more traffic from Google.'*",
    "",
    "The good version is specific, answers a question, and has a CTA. The bad version is generic and could apply to any business.",
    "",
    "---",
    "",
    "## Check your meta descriptions in 30 seconds",
    "",
    "Run any URL through [getmetafix.com](https://getmetafix.com) — it checks whether your meta description is present, correctly formatted, the right length, and unique.",
    "",
    "If it's missing or wrong, the $29 Fix Package generates a rewritten meta description for your page — tailored to your content and keyword.",
  ].join("\n"),
};

const wordpressMetaPost: Post = {
  slug: "wordpress-meta-tags-guide",
  title: "WordPress Meta Tags: The Complete Setup Guide (No Plugin Needed)",
  description:
    "Yoast and Rank Math are popular, but do you actually need them? This guide covers how to add meta tags to WordPress correctly — with or without a plugin.",
  date: "2026-03-19",
  readTime: "8 min read",
  content: [
    "## WordPress meta tags: what most guides get wrong",
    "",
    "Most WordPress SEO guides tell you to install Yoast SEO and call it done. That's reasonable advice. But it skips the most important part: understanding what meta tags actually do, which ones matter, and how to verify they're working.",
    "",
    "We've audited hundreds of WordPress sites that had Yoast installed — and still had critical meta tag failures. Plugin doesn't mean working.",
    "",
    "This guide covers everything: what WordPress meta tags you need, how to add them (with and without plugins), and how to audit them.",
    "",
    "---",
    "",
    "## The 3 types of meta tags WordPress sites need",
    "",
    "### 1. SEO meta tags",
    "",
    "These go in your `<head>` and tell Google what each page is about:",
    "",
    "- **Title tag** (`<title>`): The blue headline in Google results. 50-60 characters. Include your primary keyword.",
    "- **Meta description** (`<meta name=\"description\">`): The snippet below the title. 150-160 characters. Affects click-through rate.",
    "- **Canonical tag** (`<link rel=\"canonical\">`): The 'official' URL for this page — prevents duplicate content penalties.",
    "- **Robots tag** (`<meta name=\"robots\">`): Tells Google whether to index the page. Default is 'index, follow' — only add this if you need to change that.",
    "",
    "### 2. Open Graph tags",
    "",
    "These control how your pages look when shared on Facebook, LinkedIn, iMessage, and Slack:",
    "",
    "- `og:title` — The headline in the preview card",
    "- `og:description` — The description below",
    "- `og:image` — The preview image (minimum 1200×630px, absolute URL)",
    "- `og:url` — Your page's canonical URL",
    "- `og:type` — Content type: 'website', 'article', or 'product'",
    "",
    "Missing these = ugly link previews when anyone shares your content. More common than you'd think.",
    "",
    "### 3. Twitter Card tags",
    "",
    "X/Twitter uses its own tag system:",
    "",
    "- `twitter:card` — Set to `summary_large_image` for a big image preview",
    "- `twitter:title` and `twitter:description` — Often inherited from OG tags",
    "- `twitter:image` — The image (can be same as og:image)",
    "",
    "---",
    "",
    "## Option 1: Add meta tags with Yoast SEO (recommended for most sites)",
    "",
    "Yoast SEO is the most-used WordPress SEO plugin. Here's how to use it correctly:",
    "",
    "**Setup:**",
    "1. Install and activate Yoast SEO (free version is fine for most sites)",
    "2. Go to SEO → General → Features → enable 'Advanced settings pages'",
    "3. Go to SEO → Social → Facebook → enable 'Add Open Graph meta data'",
    "4. Go to SEO → Social → Twitter → enable Twitter card",
    "",
    "**Per-page setup:**",
    "For each page/post, scroll to the Yoast SEO panel below the editor.",
    "- SEO tab: Set 'SEO title' (what appears in Google) and 'Meta description'",
    "- Social tab: Set Facebook and Twitter title/description/image",
    "",
    "**Common Yoast mistake:** Using the 'focus keyphrase' as your title. The title goes in 'SEO title' — they're separate fields.",
    "",
    "**Run a free audit to verify Yoast is working correctly:** [getmetafix.com](https://getmetafix.com) — paste your URL and see exactly what tags Yoast generated.",
    "",
    "---",
    "",
    "## Option 2: Add meta tags with Rank Math",
    "",
    "Rank Math is a newer plugin that includes more features in the free tier than Yoast. Setup is similar:",
    "",
    "1. Install Rank Math → run the setup wizard",
    "2. During setup, enable 'Social Meta' when prompted",
    "3. Go to Rank Math → Titles & Meta → set global defaults",
    "4. Per page: use the Rank Math panel below the editor → Edit Snippet → fill in title and description",
    "",
    "Rank Math auto-generates OG tags from your SEO title/description. But set per-page OG images manually for important pages.",
    "",
    "---",
    "",
    "## Option 3: Add meta tags without a plugin",
    "",
    "If you're comfortable editing theme files, you can add meta tags directly. This is the cleanest approach but requires care — a mistake can break the whole site.",
    "",
    "Add to your theme's `functions.php` or a child theme:",
    "",
    "```php",
    "function custom_meta_tags() {",
    "  if ( is_singular() ) {",
    "    global $post;",
    "    $description = get_the_excerpt( $post );",
    "    $image = get_the_post_thumbnail_url( $post, 'large' );",
    "    echo '<meta name=\"description\" content=\"' . esc_attr( $description ) . '\">';",
    "    echo '<meta property=\"og:title\" content=\"' . esc_attr( get_the_title() ) . '\">';",
    "    echo '<meta property=\"og:description\" content=\"' . esc_attr( $description ) . '\">';",
    "    echo '<meta property=\"og:image\" content=\"' . esc_url( $image ) . '\">';",
    "    echo '<meta property=\"og:url\" content=\"' . esc_url( get_permalink() ) . '\">';",
    "    echo '<meta property=\"og:type\" content=\"article\">';",
    "    echo '<meta name=\"twitter:card\" content=\"summary_large_image\">';",
    "  }",
    "}",
    "add_action( 'wp_head', 'custom_meta_tags' );",
    "```",
    "",
    "This is a basic version. For production, you'd want per-page custom fields for more control.",
    "",
    "---",
    "",
    "## The meta tags most WordPress sites are missing",
    "",
    "Even with Yoast installed, we see these failures constantly:",
    "",
    "**1. OG image not set on inner pages**",
    "Yoast only auto-sets the OG image on the homepage. Blog posts and product pages often have no og:image — meaning social shares show a broken preview.",
    "",
    "**Fix:** Set a featured image on every post. Yoast uses the featured image as the OG image automatically.",
    "",
    "**2. Meta description auto-generated**",
    "Yoast will auto-generate a meta description from your content if you don't write one. It's almost always worse than what you'd write. Google often ignores these.",
    "",
    "**Fix:** Write a unique meta description for every important page. 155 characters. Include the keyword.",
    "",
    "**3. Title tag includes site name on short pages**",
    "Yoast's default title format is usually: `Post Title - Site Name`. If your post title is short, this is fine. If it's long (45+ chars), appending ' - Site Name' pushes it over 60 characters.",
    "",
    "**Fix:** Change the title separator to a shorter format, or shorten your post titles to leave room.",
    "",
    "**4. Canonical tag pointing to wrong URL**",
    "On paginated archives or when the same post appears under multiple categories, canonical tags can point to unexpected URLs. This dilutes your ranking power.",
    "",
    "**Fix:** Check canonical tags with [getmetafix.com](https://getmetafix.com) — it shows you exactly which canonical URL your page is reporting.",
    "",
    "---",
    "",
    "## How to audit your WordPress meta tags",
    "",
    "The fastest way: paste any page URL into [getmetafix.com](https://getmetafix.com). It checks all 12 critical meta tag elements in 30 seconds and shows you exactly what Yoast (or your custom setup) is outputting.",
    "",
    "More thorough check: View source (`Cmd+U` / `Ctrl+U`) and search for `<meta name=\"description\"` and `<meta property=\"og:image\"`. If they're missing, you know what to fix.",
    "",
    "The $29 Fix Package at GetMetaFix generates the exact meta tag HTML tailored to your page — paste it in, or give it to your developer.",
  ].join("\n"),
};

const titleTagLengthPost: Post = {
  slug: "title-tag-too-long-fix",
  title: "Title Tag Too Long? Here's the Exact Fix (With Character Limits)",
  description:
    "If your title tag is over 60 characters, Google truncates it in search results — costing you clicks. Here's exactly how to check, shorten, and fix it on WordPress, Shopify, and plain HTML.",
  date: "2026-03-19",
  readTime: "7 min read",
  content: [
    "## Why title tag length matters more than most SEO guides admit",
    "",
    "Your title tag is the single most visible piece of SEO copy on the page. It's the blue headline in Google search results. It's the browser tab label. It's the first thing a searcher reads before deciding whether to click.",
    "",
    "Google displays approximately **60 characters** of a title tag in desktop search results (around 600px of pixel width). Anything longer gets cut off with an ellipsis — '...' — mid-sentence.",
    "",
    "That truncation is not just cosmetic. A truncated title:",
    "- Hides your keyword if it appears at the end",
    "- Looks unprofessional in search results",
    "- Reduces click-through rate as the snippet looks incomplete",
    "- May cause Google to rewrite the title entirely with its own version",
    "",
    "We audited 500 random pages across Shopify, WordPress, and custom sites. **68% had title tags over 60 characters.** Most of them had no idea.",
    "",
    "---",
    "",
    "## The exact character limit (it's not as simple as '60')",
    "",
    "Google measures title tag display width in pixels, not characters. The practical limits:",
    "",
    "- **Safe zone:** 50–60 characters",
    "- **Absolute max:** ~60 characters for most titles",
    "- **For titles with wide characters** (W, M, capitals): aim for 55 characters",
    "- **For titles with narrow characters** (i, l, 1): you may fit 65",
    "",
    "The **60-character rule** is the right working limit for almost all cases. If you're under 60, you're safe. If you're over, test it.",
    "",
    "### What Google does when your title is too long",
    "",
    "Google has three options when your title tag is too long:",
    "",
    "1. **Truncate it** — Shows '...' at the point where it hits the limit",
    "2. **Rewrite it** — Generates its own title using H1, anchor text, or page content",
    "3. **Show a shorter version** — Removes words from the middle or end",
    "",
    "Option 1 is bad. Option 2 is worse. You lose control of the most important SEO element on your page.",
    "",
    "---",
    "",
    "## How to check if your title tag is too long",
    "",
    "### Method 1: Free audit at GetMetaFix",
    "",
    "The fastest way: paste your URL into [GetMetaFix](https://getmetafix.com). It checks your title tag length, tells you the exact character count, and flags it as critical if it's over 60 characters.",
    "",
    "Free. No account required. Results in 30 seconds.",
    "",
    "### Method 2: View page source",
    "",
    "Open any page, press **Cmd+U** (Mac) or **Ctrl+U** (Windows). Search for `<title>`. The text between the opening and closing tags is your title tag. Count the characters.",
    "",
    "### Method 3: Google Search Console",
    "",
    "Go to Google Search Console → Pages → click any page → check the title shown. If Google has rewritten it, that's a sign your original was too long or weak.",
    "",
    "---",
    "",
    "## How to fix a title tag that's too long",
    "",
    "The fix is simple in principle: rewrite the title to under 60 characters. In practice, this requires judgment. Here's the framework:",
    "",
    "### Step 1: Lead with the primary keyword",
    "",
    "Google gives more weight to words at the start of the title. If your title is being truncated, the keyword needs to survive the cut.",
    "",
    "❌ Too long, keyword buried: *'The Great T-Shirt Company | Premium Organic Cotton Heavyweight T-Shirts in Navy'* (82 chars)",
    "",
    "✅ Fixed: *'Organic Cotton T-Shirts | The Great T-Shirt Co'* (49 chars)",
    "",
    "### Step 2: Move or abbreviate the brand name",
    "",
    "The most common source of title tag bloat is the brand name appended at the end. If your brand name is long, abbreviate or drop it:",
    "",
    "- 'The Great T-Shirt Company' → 'The Great T-Shirt Co'",
    "- 'Northfield Digital Marketing Agency' → 'Northfield Digital'",
    "- Drop the brand entirely on inner pages (use it only on the homepage)",
    "",
    "### Step 3: Remove filler words",
    "",
    "Strip words that add length without adding meaning:",
    "",
    "- 'The', 'A', 'An' at the start",
    "- 'Complete', 'Ultimate', 'Comprehensive' (vague superlatives)",
    "- 'In 2026' (unless you need the year for freshness signals)",
    "- 'Guide to', 'Introduction to'",
    "",
    "❌ *'A Complete Introduction to Organic Cotton T-Shirts from The Great T-Shirt Company'* (82 chars)",
    "",
    "✅ *'Organic Cotton T-Shirts | The Great T-Shirt Co'* (49 chars)",
    "",
    "### Step 4: Use a separator wisely",
    "",
    "Separators (|, –, :) help Google parse title structure. They also use characters. Use one separator, not multiple:",
    "",
    "❌ *'Organic Cotton T-Shirts – Premium – Heavyweight – The Great T-Shirt Co'* (71 chars)",
    "",
    "✅ *'Organic Cotton T-Shirts | The Great T-Shirt Co'* (49 chars)",
    "",
    "---",
    "",
    "## Check your title tag — and every other SEO issue — right now",
    "",
    "A long title tag is rarely the only problem. Most pages that have title length issues also have missing meta descriptions, broken Open Graph tags, or wrong canonical URLs.",
    "",
    "Run a free full audit at [getmetafix.com](https://getmetafix.com) — it checks 12 critical SEO elements in 30 seconds. No account needed.",
    "",
    "The $29 Fix Package generates exact, rewritten meta tags for your page: a properly-shortened title tag, a new meta description, and corrected Open Graph tags — all tailored to your content.",
    "",
    "---",
    "",
    "## How to fix title tags on different platforms",
    "",
    "### WordPress (with Yoast SEO)",
    "",
    "1. Open the page or post in the editor",
    "2. Scroll to the **Yoast SEO** panel below the content",
    "3. Click the **SEO** tab",
    "4. Click **Edit snippet**",
    "5. Edit the **SEO title** field — Yoast shows a live character counter and a preview of how it will appear in Google",
    "6. Keep the green bar filled but not overflowing",
    "7. Save the post",
    "",
    "**Common Yoast mistake:** Editing the post title (H1) instead of the SEO title. These are separate fields. The post title is what appears on the page. The SEO title is what appears in Google. Edit the SEO title.",
    "",
    "### WordPress (with Rank Math)",
    "",
    "1. Open the page or post",
    "2. Click the **Rank Math** icon in the top-right toolbar",
    "3. Go to **Edit Snippet**",
    "4. Edit the **SEO Title** — Rank Math also shows a live character preview",
    "5. Update",
    "",
    "### Shopify",
    "",
    "Shopify's default title format is: **[Product Name] – [Shop Name]**",
    "",
    "This causes over-length titles constantly. To fix:",
    "",
    "**For product pages:**",
    "1. Go to your Shopify admin → Products → select the product",
    "2. Scroll to **Search engine listing preview**",
    "3. Click **Edit website SEO**",
    "4. Edit the **Page title** field",
    "5. Keep it under 60 characters",
    "6. Save",
    "",
    "**For the homepage:**",
    "Online Store → Preferences → Homepage title",
    "",
    "**For collection pages:**",
    "Products → Collections → select collection → Search engine listing preview → Edit website SEO",
    "",
    "### Plain HTML",
    "",
    "Find the `<title>` tag inside your `<head>` element and rewrite it:",
    "",
    "```html",
    "<head>",
    "  <title>Organic Cotton T-Shirts | The Great T-Shirt Co</title>",
    "</head>",
    "```",
    "",
    "Keep it under 60 characters. Lead with your primary keyword.",
    "",
    "### Next.js",
    "",
    "In Next.js App Router, set title in your metadata export:",
    "",
    "```typescript",
    "export const metadata = {",
    "  title: 'Organic Cotton T-Shirts | The Great T-Shirt Co',",
    "};",
    "```",
    "",
    "Or with a template:",
    "",
    "```typescript",
    "export const metadata = {",
    "  title: {",
    "    default: 'The Great T-Shirt Co',",
    "    template: '%s | The Great T-Shirt Co',",
    "  },",
    "};",
    "```",
    "",
    "The `%s` is replaced by each page's title — so keep page titles short to leave room for the brand suffix.",
    "",
    "---",
    "",
    "## What to do when you can't shorten without losing keywords",
    "",
    "This is the real challenge. Sometimes the keyword you're targeting is long, and your brand name is long, and you can't fit both under 60 characters.",
    "",
    "Here's how to handle it:",
    "",
    "**Option 1: Target a shorter keyword variation**",
    "",
    "If your title is *'How to Fix Shopify Meta Tags for SEO in 2026 | GetMetaFix'* (62 chars), consider:",
    "- Is 'Fix Shopify Meta Tags' the exact phrase people search, or would *'Shopify Meta Tags Fix'* work?",
    "- Check Google's autocomplete for the shortest version of your target phrase",
    "",
    "**Option 2: Drop the brand on inner pages**",
    "",
    "Your homepage carries the brand. On product pages, blog posts, and landing pages, it's often fine to omit the brand entirely. Google knows which site it's on.",
    "",
    "❌ *'How to Fix Shopify Meta Tags — GetMetaFix SEO Auditor'* (56 chars — safe, but tight)",
    "",
    "✅ *'How to Fix Shopify Meta Tags for SEO'* (38 chars — clean, keyword-first, room to breathe)",
    "",
    "**Option 3: Prioritise keyword over brand, always**",
    "",
    "If you're choosing between fitting the keyword or fitting the brand name, always keep the keyword. The keyword determines which searches you appear for. The brand name mostly helps people recognise you after they've already seen the result.",
    "",
    "**Option 4: Let Google pick — but write a strong H1**",
    "",
    "If Google is going to rewrite your title anyway (because it's too long), the next best thing is having a strong, keyword-rich H1 on the page. Google frequently uses the H1 as the displayed title in search results. Make sure your H1 is under 60 characters and includes the target keyword.",
    "",
    "---",
    "",
    "## Title tag length: quick reference",
    "",
    "- **Under 50 chars**: Too short — you have unused space. Add more keyword context.",
    "- **50–60 chars**: Ideal. Full title visible in most Google results.",
    "- **60–70 chars**: Risky. Will truncate on some queries and devices.",
    "- **Over 70 chars**: Will truncate. Google may rewrite entirely.",
    "",
    "Run a free audit at [getmetafix.com](https://getmetafix.com) to see your exact title tag length and get a prioritised list of everything else that needs fixing.",
  ].join("\n"),
};

const canonicalTagPost: Post = {
  slug: "canonical-tag-seo-fix",
  title: "Canonical Tag: What It Is, Why It's Missing, and How to Fix It",
  description:
    "Missing or wrong canonical tags cause duplicate content penalties and wasted crawl budget. Here's exactly what to set, why, and how to check yours in 30 seconds.",
  date: "2026-03-19",
  readTime: "7 min read",
  content: [
    "## What a canonical tag actually does",
    "",
    "A canonical tag is a single line of HTML that tells Google: *this is the original version of this page*. Without it, Google may treat multiple URLs showing the same content as separate pages competing against each other.",
    "",
    "It sits in your `<head>` tag and looks like this:",
    "",
    "```html",
    '<link rel="canonical" href="https://yoursite.com/your-page-url" />',
    "```",
    "",
    "That's it. One tag, one URL, one clear signal.",
    "",
    "The problem: most sites either have it missing, set it wrong, or accidentally point it at the wrong page — and they have no idea until their rankings start quietly dropping.",
    "",
    "---",
    "",
    "## Why missing canonical tags hurt your SEO",
    "",
    "### The duplicate content problem",
    "",
    "Without canonical tags, Google may see these as separate pages:",
    "",
    "- `https://yoursite.com/product`",
    "- `https://yoursite.com/product?ref=homepage`",
    "- `https://yoursite.com/product?sort=price`",
    "- `http://yoursite.com/product` (HTTP vs HTTPS)",
    "- `https://www.yoursite.com/product` (www vs non-www)",
    "",
    "All showing the same content. Google doesn't know which one to rank. It splits authority between them instead of concentrating it on one URL. Result: none of them rank as well as they should.",
    "",
    "### The crawl budget problem",
    "",
    "Google allocates a crawl budget to each site — a limit on how many pages it'll crawl per day. On large sites, without canonical tags, Google wastes that budget crawling duplicate versions of the same pages instead of discovering new content.",
    "",
    "### The link equity problem",
    "",
    "When other sites link to your content, they might link to different URL variants. Without canonical tags, that link equity is split. With canonical tags, it all consolidates to the canonical URL.",
    "",
    "---",
    "",
    "## The 5 most common canonical tag mistakes",
    "",
    "### 1. Missing entirely",
    "",
    "The most common issue. No canonical tag at all. Google has to guess, and it frequently guesses wrong.",
    "",
    "**Check:** Use [getmetafix.com](https://getmetafix.com) — it flags missing canonical tags in the first 5 results.",
    "",
    "### 2. Pointing to the wrong URL",
    "",
    "```html",
    "<!-- Wrong: relative URL -->",
    '<link rel="canonical" href="/product-page" />',
    "",
    "<!-- Correct: full absolute URL -->",
    '<link rel="canonical" href="https://yoursite.com/product-page" />',
    "```",
    "",
    "Canonical tags must use absolute URLs with the full protocol and domain. Relative URLs are technically valid but create ambiguity. Always use the full URL.",
    "",
    "### 3. Non-canonical pages pointing to themselves",
    "",
    "If you have a paginated series (`/blog?page=2`, `/blog?page=3`), they should each have canonical tags pointing back to the root (`/blog`), not to themselves. Self-referencing canonicals on paginated pages waste the signal.",
    "",
    "### 4. Canonical and noindex together",
    "",
    "```html",
    "<!-- Conflicting signals — don't do this -->",
    '<meta name="robots" content="noindex" />',
    '<link rel="canonical" href="https://yoursite.com/page" />',
    "```",
    "",
    "Noindex tells Google not to index the page. Canonical tells Google this is the authoritative version. These conflict. Google will follow one and ignore the other — but you can't predict which. Remove noindex if you want the canonical to be respected.",
    "",
    "### 5. Canonical pointing to a redirect",
    "",
    "The canonical URL must be a live, crawlable page. If it redirects, Google may not respect the signal. Always check that your canonical URL returns a 200 OK status and doesn't redirect.",
    "",
    "---",
    "",
    "## How to fix canonical tags on every platform",
    "",
    "### Shopify",
    "",
    "Shopify automatically adds canonical tags to product and collection pages. The problem is the generated URLs often include tracking parameters that get flagged as duplicate pages.",
    "",
    "For Shopify, the main fix is usually in your `theme.liquid` file — checking that the canonical is using the clean URL, not a parameter-laden variant:",
    "",
    "```html",
    "<!-- In theme.liquid <head> section -->",
    "<link rel=\"canonical\" href=\"{{ canonical_url }}\" />",
    "```",
    "",
    "Shopify's `{{ canonical_url }}` Liquid variable strips most tracking parameters automatically. If you're using a custom theme that overwrites this, that's the first place to check.",
    "",
    "### WordPress",
    "",
    "With Yoast SEO or Rank Math installed:",
    "",
    "1. Go to the post/page edit screen",
    "2. Click the Yoast/Rank Math panel",
    "3. Find 'Advanced' settings",
    "4. Set 'Canonical URL' to the correct full URL",
    "",
    "Without a plugin, add this to your `<head>` in `header.php`:",
    "",
    "```php",
    "<?php",
    "$canonical = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];",
    "echo '<link rel=\"canonical\" href=\"' . esc_url($canonical) . '\" />';",
    "?>",
    "```",
    "",
    "### Plain HTML",
    "",
    "Add directly to each page's `<head>` section:",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Your Page Title</title>",
    '    <link rel="canonical" href="https://yoursite.com/exact-page-url" />',
    "  </head>",
    "</html>",
    "```",
    "",
    "The canonical URL should be exactly the URL you want Google to index — clean, without tracking parameters, using HTTPS.",
    "",
    "### Next.js (App Router)",
    "",
    "```typescript",
    "// In your page.tsx or layout.tsx",
    "import type { Metadata } from 'next';",
    "",
    "export const metadata: Metadata = {",
    "  alternates: {",
    "    canonical: 'https://yoursite.com/your-page',",
    "  },",
    "};",
    "```",
    "",
    "Next.js will render this as `<link rel=\"canonical\" href=\"...\">` in the `<head>` automatically.",
    "",
    "---",
    "",
    "## Self-referencing vs cross-domain canonicals",
    "",
    "There are two types of canonical tags:",
    "",
    "**Self-referencing canonical:** The page points to itself. This is the standard case for most pages — it tells Google this URL is the canonical version of itself, and discourages URL variants from competing.",
    "",
    "```html",
    "<!-- On https://yoursite.com/about -->",
    '<link rel="canonical" href="https://yoursite.com/about" />',
    "```",
    "",
    "**Cross-domain canonical:** A page on one domain points to content on another domain as the authoritative version. This is used when the same content is published in multiple places (e.g., a blog post syndicated to Medium).",
    "",
    "```html",
    "<!-- On medium.com/your-article — pointing back to your site -->",
    '<link rel="canonical" href="https://yoursite.com/original-article" />',
    "```",
    "",
    "For most sites, you only need self-referencing canonicals. Cross-domain canonicals are an advanced use case for content syndication.",
    "",
    "---",
    "",
    "## How to check if your canonical tags are correct",
    "",
    "The fastest way: run a free audit at [getmetafix.com](https://getmetafix.com). It checks your canonical tag alongside 11 other SEO signals and flags anything missing, wrong, or conflicting.",
    "",
    "The manual way: right-click any page → View Source → search for `canonical`. You should see:",
    "",
    "```html",
    '<link rel="canonical" href="https://yoursite.com/exact-url" />',
    "```",
    "",
    "Check for:",
    "- [x] Uses full HTTPS URL",
    "- [x] URL matches what's in your browser address bar (or the clean version without parameters)",
    "- [x] No conflicting noindex tag on the same page",
    "- [x] The canonical URL itself returns 200 OK (not a redirect)",
    "",
    "---",
    "",
    "## Canonical tags and hreflang (international SEO)",
    "",
    "If your site has multiple language versions, canonical tags work alongside `hreflang` tags — but they don't replace each other.",
    "",
    "- **Canonical:** Tells Google which URL is the authoritative version of a page's content",
    "- **hreflang:** Tells Google which language/region variant to show to which user",
    "",
    "Common mistake: setting a canonical from a French page to the English page. Don't. Each language version should self-canonicalise, and use hreflang to link the variants together.",
    "",
    "```html",
    "<!-- On /fr/product — correct -->",
    '<link rel="canonical" href="https://yoursite.com/fr/product" />',
    '<link rel="alternate" hreflang="fr" href="https://yoursite.com/fr/product" />',
    '<link rel="alternate" hreflang="en" href="https://yoursite.com/product" />',
    "```",
    "",
    "---",
    "",
    "## The quick fix checklist",
    "",
    "- [x] Every indexable page has a canonical tag",
    "- [x] Canonical uses the full HTTPS absolute URL",
    "- [x] No noindex + canonical conflict on the same page",
    "- [x] Canonical URL returns 200 OK (no redirects)",
    "- [x] Paginated pages: `?page=2` canonicals point to the root, not themselves",
    "- [x] URL parameters (tracking, sorting, filtering) stripped from the canonical URL",
    "",
    "Run [getmetafix.com](https://getmetafix.com) on your site. Free, 30 seconds, no account needed — it flags canonical issues alongside everything else that's quietly costing you Google traffic.",
  ].join("\n"),
};

const twitterCardPost: Post = {
  slug: "twitter-card-not-working",
  title: "Twitter Card Not Working? Here's Exactly Why (and How to Fix It)",
  description:
    "Your link previews on Twitter/X look broken — no image, wrong title, plain URL. Here's every reason Twitter cards fail and the exact code to fix each one.",
  date: "2026-03-19",
  readTime: "7 min read",
  content: [
    "## Your link looks terrible on Twitter. Here's why.",
    "",
    "You share a link on Twitter/X and instead of a rich preview with an image, headline, and description — you get a plain blue URL. Or worse: a broken image placeholder, the wrong title, or a preview from some random page on your site.",
    "",
    "This happens because Twitter/X reads specific meta tags called **Twitter Cards** to build those previews. If the tags are missing, wrong, or misconfigured, Twitter falls back to plain text — or scrapes whatever it finds first.",
    "",
    "The good news: Twitter card problems are almost always fixable in under 10 minutes once you know what's wrong.",
    "",
    "---",
    "",
    "## What are Twitter Cards?",
    "",
    "Twitter Cards are HTML meta tags you add to your page's `<head>` that tell Twitter how to display your link when someone shares it. There are four types:",
    "",
    "- **summary** — Title, description, small thumbnail image (100×100px minimum)",
    "- **summary_large_image** — Title, description, large banner image (at least 600×314px recommended)",
    "- **app** — For linking to mobile apps",
    "- **player** — For embedded video/audio",
    "",
    "For most websites, you want `summary_large_image`. It creates the big image preview you see from news sites, blog posts, and product pages.",
    "",
    "The minimum set of Twitter Card tags looks like this:",
    "",
    "```html",
    '<meta name="twitter:card" content="summary_large_image" />',
    '<meta name="twitter:title" content="Your Page Title" />',
    '<meta name="twitter:description" content="A compelling description under 200 characters." />',
    '<meta name="twitter:image" content="https://yoursite.com/images/og-image.jpg" />',
    "```",
    "",
    "Twitter also reads `og:title`, `og:description`, and `og:image` (Open Graph tags) as fallbacks if the twitter: versions are missing. But don't rely on that — always set both.",
    "",
    "---",
    "",
    "## The 7 most common reasons Twitter cards don't work",
    "",
    "### 1. Missing `twitter:card` meta tag",
    "",
    "This is the most common issue. Without `<meta name=\"twitter:card\">`, Twitter doesn't know what type of card to show and defaults to plain text.",
    "",
    "**Fix:**",
    "",
    "```html",
    '<meta name="twitter:card" content="summary_large_image" />',
    "```",
    "",
    "Add this as the first Twitter Card tag in your `<head>`. Without it, none of the other tags do anything.",
    "",
    "### 2. Twitter Card image is wrong size",
    "",
    "Twitter will silently skip your image if it's too small, wrong aspect ratio, or a format Twitter doesn't support.",
    "",
    "**Requirements for `summary_large_image`:**",
    "",
    "- Minimum: 300×157px",
    "- Recommended: 1200×628px (same as OG image)",
    "- Maximum file size: 5MB",
    "- Supported formats: JPG, PNG, WEBP, GIF (static only)",
    "- Aspect ratio: 2:1 (landscape)",
    "",
    "**Fix:** Resize your image to 1200×628px. Use the same image for both `og:image` and `twitter:image`:",
    "",
    "```html",
    '<meta property="og:image" content="https://yoursite.com/og-image.jpg" />',
    '<meta name="twitter:image" content="https://yoursite.com/og-image.jpg" />',
    "```",
    "",
    "### 3. Image URL not accessible",
    "",
    "Twitter's crawler fetches your image when the link is first shared. If the image requires authentication, is behind a CDN that blocks bots, or returns a 404 — no preview.",
    "",
    "**Check:** Paste your image URL into a fresh browser window (incognito). Can you see the image? Try it in [Twitter's Card Validator](https://cards-dev.twitter.com/validator) — it shows you exactly what Twitter sees.",
    "",
    "**Fix:** Ensure your og:image/twitter:image URL is:",
    "",
    "- [x] Absolute URL (starts with `https://`)",
    "- [x] Publicly accessible (no login required)",
    "- [x] Returns HTTP 200 with correct content-type header",
    "- [x] Not blocked by robots.txt",
    "",
    "### 4. Cached old card data",
    "",
    "You fixed your meta tags but Twitter still shows the old (broken) preview. This is a caching issue — Twitter caches card data aggressively.",
    "",
    "**Fix:** Use the [Twitter Card Validator](https://cards-dev.twitter.com/validator). Paste your URL and click 'Preview card'. This forces Twitter to re-scrape and flush the cache for that URL.",
    "",
    "Twitter's cache typically expires after 7 days, but the validator forces an immediate refresh.",
    "",
    "### 5. Conflicting or duplicate meta tags",
    "",
    "If your page has two `og:image` tags (common in CMS setups where themes and plugins both add them), Twitter may use the wrong one — or get confused and show nothing.",
    "",
    "**Check:** Right-click your page → View Source → search for `og:image`. You should only see one.",
    "",
    "**Fix:** Remove duplicates. If you're on WordPress, check if both your theme AND Yoast/RankMath are adding OG tags. Disable one of them.",
    "",
    "### 6. Image behind HTTPS mixed content",
    "",
    "Your site is HTTPS but you're referencing an image via HTTP. Twitter only fetches images over HTTPS.",
    "",
    "**Wrong:**",
    "```html",
    '<meta name="twitter:image" content="http://yoursite.com/image.jpg" />',
    "```",
    "",
    "**Right:**",
    "```html",
    '<meta name="twitter:image" content="https://yoursite.com/image.jpg" />',
    "```",
    "",
    "### 7. Robots.txt blocking Twitter's crawler",
    "",
    "If your robots.txt disallows the `Twitterbot` user-agent, Twitter can't crawl your page to read the meta tags.",
    "",
    "**Check your robots.txt** (visit yoursite.com/robots.txt). Look for anything blocking Twitterbot:",
    "",
    "```",
    "# Bad — blocks Twitter",
    "User-agent: *",
    "Disallow: /",
    "",
    "# Good — allows Twitter",
    "User-agent: Twitterbot",
    "Allow: /",
    "```",
    "",
    "Make sure neither `User-agent: *` with a broad Disallow nor a specific `User-agent: Twitterbot` block is preventing access to your important pages.",
    "",
    "---",
    "",
    "## Platform-specific fixes",
    "",
    "### Shopify",
    "",
    "Shopify auto-generates Open Graph tags for product pages, but doesn't always add Twitter Card tags. Add them to your `theme.liquid` file:",
    "",
    "```html",
    "<!-- In theme.liquid, inside <head> -->",
    '{% if page_description %}',
    '  <meta name="twitter:description" content="{{ page_description | escape }}" />',
    '{% endif %}',
    '<meta name="twitter:card" content="summary_large_image" />',
    '<meta name="twitter:title" content="{{ page_title | escape }}" />',
    '{% if settings.share_image %}',
    '  <meta name="twitter:image" content="{{ settings.share_image | img_url: \'1200x628\' }}" />',
    '{% endif %}',
    "```",
    "",
    "### WordPress (manual)",
    "",
    "Add to your theme's `functions.php` or a child theme — but a plugin is easier:",
    "",
    "```php",
    "function add_twitter_card_meta() {",
    "  echo '<meta name=\"twitter:card\" content=\"summary_large_image\" />';",
    "  echo '<meta name=\"twitter:title\" content=\"' . get_the_title() . '\" />';",
    "}",
    "add_action('wp_head', 'add_twitter_card_meta');",
    "```",
    "",
    "**Better approach:** Use Yoast SEO (free) or RankMath (free). Both generate Twitter Card tags automatically from your post's featured image and SEO title.",
    "",
    "### Next.js (App Router)",
    "",
    "```typescript",
    "// app/blog/[slug]/page.tsx",
    "export const metadata: Metadata = {",
    "  twitter: {",
    "    card: 'summary_large_image',",
    "    title: 'Your Post Title',",
    "    description: 'Your post description',",
    "    images: ['https://yoursite.com/og-image.jpg'],",
    "  },",
    "};",
    "```",
    "",
    "Next.js renders this as the correct Twitter Card meta tags automatically.",
    "",
    "---",
    "",
    "## How to test Twitter Cards properly",
    "",
    "**Step 1: Check your meta tags exist**",
    "",
    "Run a free audit at [getmetafix.com](https://getmetafix.com). It checks all 12 meta tag signals including Twitter Card presence, image validity, and common misconfigurations. Takes 30 seconds.",
    "",
    "**Step 2: Use Twitter's Card Validator**",
    "",
    "Go to [cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator) and paste your URL. This shows you exactly what Twitter sees — including any error messages about why your card isn't working.",
    "",
    "**Step 3: Check with opengraph.xyz**",
    "",
    "[opengraph.xyz](https://opengraph.xyz) lets you preview how your link looks across Twitter, Facebook, LinkedIn, and Slack simultaneously. Useful for catching platform-specific issues.",
    "",
    "**Step 4: Post a test tweet**",
    "",
    "After fixing your tags, post a test tweet with your URL. If it still shows the old broken preview, use the Card Validator to flush Twitter's cache first.",
    "",
    "---",
    "",
    "## The complete Twitter Card template",
    "",
    "Here's a complete, correct Twitter Card implementation for any website:",
    "",
    "```html",
    "<head>",
    "  <!-- Open Graph (Facebook, LinkedIn, WhatsApp) -->",
    '  <meta property="og:title" content="Your Page Title" />',
    '  <meta property="og:description" content="Under 155 characters. Make it compelling." />',
    '  <meta property="og:image" content="https://yoursite.com/images/og-1200x628.jpg" />',
    '  <meta property="og:url" content="https://yoursite.com/this-page" />',
    '  <meta property="og:type" content="website" />',
    "",
    "  <!-- Twitter Card -->",
    '  <meta name="twitter:card" content="summary_large_image" />',
    '  <meta name="twitter:title" content="Your Page Title" />',
    '  <meta name="twitter:description" content="Under 155 characters. Make it compelling." />',
    '  <meta name="twitter:image" content="https://yoursite.com/images/og-1200x628.jpg" />',
    '  <meta name="twitter:image:alt" content="Describe the image for accessibility" />',
    "",
    "  <!-- Optional: Twitter account attribution -->",
    '  <meta name="twitter:site" content="@yourhandle" />',
    '  <meta name="twitter:creator" content="@authorhandle" />',
    "</head>",
    "```",
    "",
    "Note: the `og:image` and `twitter:image` can point to the same URL. Create one 1200×628px JPG and use it for both.",
    "",
    "---",
    "",
    "## Quick fix checklist",
    "",
    "- [x] `twitter:card` meta tag present (required — nothing else works without this)",
    "- [x] `twitter:title` set (or `og:title` as fallback)",
    "- [x] `twitter:description` set, under 200 characters",
    "- [x] `twitter:image` set to a public HTTPS URL",
    "- [x] Image is at least 300×157px, recommended 1200×628px",
    "- [x] Image file size under 5MB",
    "- [x] No duplicate og:image or twitter:image tags",
    "- [x] Twitterbot not blocked in robots.txt",
    "- [x] Card Validator shows no errors",
    "",
    "Most Twitter card problems come down to one or two missing tags. Run [getmetafix.com](https://getmetafix.com) on any URL — it checks Twitter Card tags, Open Graph, meta descriptions, canonical tags, and 8 other signals in 30 seconds, and shows you the exact code to fix whatever's broken.",
  ].join("\n"),
};

const facebookPreviewPost: Post = {
  slug: "facebook-link-preview-not-working",
  title: "Facebook Link Preview Not Working? Here's the Fix (2026)",
  description:
    "Your link looks wrong on Facebook — wrong image, outdated preview, or no image at all. Here's every reason Facebook link previews break and exactly how to fix them.",
  date: "2026-03-19",
  readTime: "6 min read",
  content: [
    "## Your link looks terrible when shared on Facebook. Fix it in 10 minutes.",
    "",
    "You paste a URL into a Facebook post and the preview shows the wrong image, an ancient thumbnail from 3 years ago, or a blank rectangle with a broken icon.",
    "",
    "This is one of the most common and frustrating web problems. The good news: it's almost always caused by one of five fixable things.",
    "",
    "---",
    "",
    "## Why Facebook link previews break",
    "",
    "Facebook reads **Open Graph (OG) meta tags** to build link previews. These are HTML tags in your page's `<head>` that tell Facebook what title, description, and image to use.",
    "",
    "When Facebook scrapes your URL, it looks specifically for:",
    "",
    "```html",
    '<meta property="og:title" content="Your Page Title" />',
    '<meta property="og:description" content="Your page description" />',
    '<meta property="og:image" content="https://yoursite.com/image.jpg" />',
    '<meta property="og:url" content="https://yoursite.com/this-page" />',
    "```",
    "",
    "If these tags are missing, outdated, or wrong — Facebook's preview breaks.",
    "",
    "---",
    "",
    "## The 5 most common causes (and fixes)",
    "",
    "### 1. No Open Graph tags at all",
    "",
    "If your page doesn't have `og:image`, Facebook will try to find an image on the page itself. It picks one at random — usually a logo, a product thumbnail, or nothing. The result looks unprofessional.",
    "",
    "**Fix:** Add OG tags to your page's `<head>`:",
    "",
    "```html",
    '<meta property="og:title" content="Exact Page Title" />',
    '<meta property="og:description" content="Compelling 1-2 sentence description." />',
    '<meta property="og:image" content="https://yoursite.com/og-image.jpg" />',
    '<meta property="og:url" content="https://yoursite.com/exact-url" />',
    '<meta property="og:type" content="website" />',
    "```",
    "",
    "### 2. Old preview is cached — changes not showing",
    "",
    "Facebook caches link previews aggressively. After you fix your OG tags, Facebook may still show the old (broken) preview for days or weeks.",
    "",
    "**Fix:** Use the **Facebook Sharing Debugger** to force a cache refresh:",
    "",
    "1. Go to [developers.facebook.com/tools/debug](https://developers.facebook.com/tools/debug)",
    "2. Paste your URL",
    "3. Click **Fetch new scrape information**",
    "4. If it still shows old data, click **Scrape Again**",
    "",
    "This forces Facebook to re-fetch your page immediately and update the cache. Do this every time you update your OG image or title.",
    "",
    "### 3. OG image is the wrong size",
    "",
    "Facebook requires a minimum image size of **200×200px** to show any preview image, and recommends **1200×630px** for the full-width banner style.",
    "",
    "**Facebook OG image requirements:**",
    "",
    "- Minimum: 200×200px",
    "- Recommended: 1200×630px (aspect ratio 1.91:1)",
    "- Maximum: 8MB",
    "- Supported formats: JPG, PNG, GIF (static), WebP",
    "",
    "Images smaller than 200×200px will be ignored and Facebook will fall back to a text-only preview. Images between 200-600px will show as a small square thumbnail on the left of the text.",
    "",
    "**Fix:** Create a dedicated OG image at 1200×630px. Tools like Canva, Figma, or even Google Slides can export images at this size. Name it `og-image.jpg` and host it at a permanent URL.",
    "",
    "### 4. OG image URL is not publicly accessible",
    "",
    "Facebook's scraper (user-agent: `facebookexternalhit`) must be able to access your image. If the image is:",
    "",
    "- Behind authentication",
    "- On a staging server not accessible publicly",
    "- Blocked by robots.txt",
    "- Returning a 404 or 403",
    "",
    "...the preview will show no image.",
    "",
    "**Check:** Paste your `og:image` URL directly into an incognito browser window. Can you see it? Then check with the Facebook Debugger — it shows exactly what Facebook's scraper saw.",
    "",
    "**Fix:** Make sure the image URL is:",
    "- [x] Absolute URL starting with `https://`",
    "- [x] Publicly accessible with no login required",
    "- [x] Not blocked in `robots.txt`",
    "- [x] Returns HTTP 200 OK with a valid image content-type",
    "",
    "### 5. Wrong or conflicting og:url tag",
    "",
    "The `og:url` tag should exactly match the canonical URL of the page. If it points to a different URL — or if there are duplicate OG tags — Facebook gets confused and may use a cached version from a different URL.",
    "",
    "**Wrong:**",
    "```html",
    "<!-- On /blog/post-title -->",
    '<meta property="og:url" content="https://yoursite.com/" />',
    "```",
    "",
    "**Right:**",
    "```html",
    "<!-- On /blog/post-title -->",
    '<meta property="og:url" content="https://yoursite.com/blog/post-title" />',
    "```",
    "",
    "---",
    "",
    "## Platform-specific fixes",
    "",
    "### Shopify",
    "",
    "Shopify generates OG tags automatically for product pages, but they're often not configured correctly. Go to **Online Store → Themes → Customize → Theme Settings → Social Media** to set a default OG image.",
    "",
    "For custom OG images per page, edit your `theme.liquid`:",
    "",
    "```html",
    "{% if page.image %}",
    "  <meta property=\"og:image\" content=\"{{ page.image | img_url: '1200x630' }}\" />",
    "{% elsif settings.share_image %}",
    "  <meta property=\"og:image\" content=\"{{ settings.share_image | img_url: '1200x630' }}\" />",
    "{% endif %}",
    "```",
    "",
    "### WordPress",
    "",
    "Install **Yoast SEO** (free) or **RankMath** (free). Both plugins handle OG tags automatically using your post's featured image. No coding required.",
    "",
    "If you're already using one of these plugins and previews are still broken — check the plugin settings: **Yoast → Social → Facebook → Add Open Graph metadata** should be enabled.",
    "",
    "### Squarespace",
    "",
    "Squarespace auto-generates OG tags from your page's content. To customise them: go to **Pages → [page] → Settings → Social Image**. You can upload a specific image for Facebook previews.",
    "",
    "### Webflow",
    "",
    "In Webflow, go to **Page Settings → SEO** for each page. There's an \"Open Graph\" section where you can set a custom title, description, and image per page. You can also set site-wide OG defaults in **Project Settings → SEO**.",
    "",
    "---",
    "",
    "## How to test your Facebook link preview",
    "",
    "**Method 1: Facebook Sharing Debugger**",
    "[developers.facebook.com/tools/debug](https://developers.facebook.com/tools/debug) — shows you exactly what Facebook sees when it crawls your URL, including any warnings about your OG tags.",
    "",
    "**Method 2: GetMetaFix**",
    "Run a free audit at [getmetafix.com](https://getmetafix.com). It checks all your OG tags (og:title, og:description, og:image, og:url), flags missing or misconfigured tags, and generates the exact HTML fix code you need. Takes 30 seconds.",
    "",
    "**Method 3: opengraph.xyz**",
    "[opengraph.xyz](https://opengraph.xyz) previews how your link looks across Facebook, Twitter, LinkedIn, and Slack simultaneously.",
    "",
    "---",
    "",
    "## The complete Open Graph template",
    "",
    "Here's a complete, correct OG setup for any page:",
    "",
    "```html",
    "<head>",
    "  <!-- Required -->",
    '  <meta property="og:title" content="Page Title Here — Max 60 chars" />',
    '  <meta property="og:description" content="Compelling description, 1-2 sentences, under 155 chars." />',
    '  <meta property="og:image" content="https://yoursite.com/og-image-1200x630.jpg" />',
    '  <meta property="og:url" content="https://yoursite.com/exact-page-url" />',
    '  <meta property="og:type" content="website" />',
    "",
    "  <!-- Recommended -->",
    '  <meta property="og:site_name" content="Your Site Name" />',
    '  <meta property="og:image:width" content="1200" />',
    '  <meta property="og:image:height" content="630" />',
    '  <meta property="og:image:type" content="image/jpeg" />',
    "",
    "  <!-- Also add Twitter Card tags (separate) -->",
    '  <meta name="twitter:card" content="summary_large_image" />',
    '  <meta name="twitter:image" content="https://yoursite.com/og-image-1200x630.jpg" />',
    "</head>",
    "```",
    "",
    "---",
    "",
    "## Quick fix checklist",
    "",
    "- [x] `og:title` present and under 60 characters",
    "- [x] `og:description` present and under 155 characters",
    "- [x] `og:image` present, pointing to a public HTTPS URL",
    "- [x] `og:image` is at least 1200×630px",
    "- [x] `og:url` matches the page's canonical URL exactly",
    "- [x] No duplicate OG tags on the page",
    "- [x] Facebook Debugger shows no errors",
    "",
    "If you want to check all of this in 30 seconds — run [getmetafix.com](https://getmetafix.com) on any URL. It audits 12 meta tag signals including all Open Graph tags, and if anything's broken, it shows you the exact lines of HTML to fix it. Free, no account needed.",
  ].join("\n"),
};

export const posts: Post[] = [shopifyPost, ogPost, seoAuditPost, metaDescPost, wordpressMetaPost, titleTagLengthPost, canonicalTagPost, twitterCardPost, facebookPreviewPost];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
