export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  content: string;
}

const shopifyPost: Post = {
  slug: "shopify-meta-tags-complete-guide",
  title: "Shopify Meta Tags: The Complete Fix Guide (2026)",
  description:
    "Most Shopify stores have broken or missing meta tags costing them Google rankings. Here's every issue, why it matters, and exactly how to fix it.",
  date: "2026-03-18",
  readTime: "8 min read",
  content: [
    "## Why Shopify meta tags are silently killing your rankings",
    "",
    "Shopify auto-generates meta tags for your store. That sounds helpful until you realise what it actually generates: generic title tags copied from product names, meta descriptions that repeat the title, and Open Graph images that default to your first product photo.",
    "",
    "Google looks at meta tags to understand what your page is about and decide where to rank it. If your meta tags are wrong, generic, or missing — you're invisible.",
    "",
    "Here's what we found when we audited 20 random Shopify stores:",
    "",
    "- **85%** had title tags over 60 characters (Google truncates these in search results)",
    "- **70%** had missing or incorrect Open Graph images (ugly previews when shared on social media)",
    "- **40%** had meta descriptions that were auto-generated or blank",
    "- **90%** had no structured data (schema markup)",
    "",
    "These aren't cosmetic problems. Each one costs you rankings and clicks.",
    "",
    "---",
    "",
    "## The 5 most common Shopify meta tag problems",
    "",
    "### 1. Title tags that are too long",
    "",
    "Google displays approximately 60 characters of your title tag in search results. Shopify's default format is usually: **[Product Name] – [Shop Name]**",
    "",
    "If your product name is 'Organic Cotton Premium Heavyweight T-Shirt in Navy Blue' and your shop is 'The Great T-Shirt Company', your title tag is 80+ characters — and Google will cut it off mid-sentence.",
    "",
    "**The fix:** Rewrite title tags to under 60 characters. Lead with the most important keyword. Add your brand at the end if space allows.",
    "",
    "Good: Navy Organic Cotton T-Shirt | The Great T-Shirt Co",
    "",
    "### 2. Meta descriptions that are duplicated or missing",
    "",
    "Shopify often uses the same meta description template across hundreds of product pages. Google penalises duplicate content and will often ignore duplicated meta descriptions entirely — writing its own version using random text from your page.",
    "",
    "**The fix:** Write a unique 150-160 character meta description for every key page. Include the primary keyword and a clear value proposition. Include a soft call to action.",
    "",
    "Good: Shop our bestselling navy organic cotton t-shirt. Heavyweight 280gsm, sustainably sourced. Free delivery over £50. 4.9 stars from 2,400 reviews.",
    "",
    "### 3. Open Graph tags not set for product pages",
    "",
    "Open Graph tags control how your pages look when shared on Facebook, LinkedIn, Twitter, or in iMessage previews. If og:image isn't set, the platform will either grab a random image from your page or show a blank preview.",
    "",
    "A bad social preview kills click-through rates. People scroll past broken-looking links.",
    "",
    "**The fix:** Set og:title, og:description, og:image, and og:type for every page. The og:image should be at least 1200×630px. Shopify themes often have a field for this in the theme settings.",
    "",
    "### 4. Missing canonical tags",
    "",
    "If your product appears at multiple URLs (e.g., from different collection paths), Google sees these as duplicate pages and may penalise both. Canonical tags tell Google which URL is the 'real' version.",
    "",
    "**The fix:** Ensure every page has a canonical tag pointing to its primary URL. In Shopify, this is usually handled automatically — but check it's working correctly.",
    "",
    "### 5. No structured data (schema markup)",
    "",
    "Structured data tells Google exactly what your page contains: a product, a price, a review, an event. It unlocks rich results — star ratings, price ranges, availability displayed directly in search results.",
    "",
    "Rich results get significantly more clicks than plain results.",
    "",
    "**The fix:** Add JSON-LD structured data to your product pages. For Shopify stores, you need at minimum: Product schema with name, description, image, offers (with price and availability), and aggregateRating.",
    "",
    "---",
    "",
    "## How to audit your Shopify meta tags (free)",
    "",
    "The fastest way is to use [GetMetaFix](https://getmetafix.com) — paste in your Shopify store URL and get a full audit in 30 seconds. It checks all the issues above, scores them by severity, and shows you exactly what's wrong.",
    "",
    "No account required, free to audit.",
    "",
    "If you want the AI-generated fixes (exact HTML snippets to copy-paste), that's $29 one-time.",
    "",
    "---",
    "",
    "## Shopify SEO meta tags checklist",
    "",
    "Use this before launching any new page or product:",
    "",
    "- [ ] Title tag under 60 characters with primary keyword",
    "- [ ] Meta description 150-160 characters, unique, includes keyword + CTA",
    "- [ ] og:title set",
    "- [ ] og:description set",
    "- [ ] og:image set (1200×630px minimum)",
    "- [ ] og:type set (usually website for homepage, product for products)",
    "- [ ] twitter:card set (usually summary_large_image)",
    "- [ ] Canonical URL pointing to primary URL",
    "- [ ] JSON-LD product schema on product pages",
    "",
    "Run a free audit at [getmetafix.com](https://getmetafix.com) to check all of these automatically.",
  ].join("\n"),
};

const ogPost: Post = {
  slug: "open-graph-tags-missing-fix",
  title: "Open Graph Tags Missing? Here's Exactly How to Fix Them",
  description:
    "Missing og:image and og:title mean broken social previews every time someone shares your page. Fix it in 10 minutes with this step-by-step guide.",
  date: "2026-03-18",
  readTime: "6 min read",
  content: [
    "## What Open Graph tags are and why missing ones cost you traffic",
    "",
    "Every time someone shares your website on social media — Facebook, LinkedIn, Twitter, iMessage, Slack — those platforms read your Open Graph (OG) tags to build the preview card.",
    "",
    "Your OG tags determine:",
    "- The **title** shown in the preview",
    "- The **description** below it",
    "- The **image** displayed",
    "- The **URL** shown",
    "",
    "If these tags are missing or wrong, you get a broken preview: wrong title, wrong image (or none), wrong description. People scroll past. Clicks die.",
    "",
    "We've audited thousands of pages. **70% have at least one broken or missing OG tag.** Most owners have no idea.",
    "",
    "---",
    "",
    "## The 5 Open Graph tags you need on every page",
    "",
    "### 1. og:title",
    "",
    "The headline shown in social previews. Should match your page title (or be slightly rewritten for social). Keep it under 60 characters.",
    "",
    "HTML: meta property='og:title' content='Your Page Title Here'",
    "",
    "### 2. og:description",
    "",
    "2-3 sentences shown below the title in the preview. Expand on the title, add a hook. Keep it under 160 characters.",
    "",
    "### 3. og:image",
    "",
    "The single most important OG tag. A compelling image dramatically increases click-through on social shares.",
    "",
    "**Requirements:**",
    "- Minimum 1200×630px (1.91:1 ratio)",
    "- Under 8MB",
    "- JPG or PNG",
    "- Absolute URL (not relative)",
    "- The image must actually exist at that URL",
    "",
    "### 4. og:url",
    "",
    "The canonical URL of your page. Prevents duplicate content issues when the same page is shared from different URLs.",
    "",
    "### 5. og:type",
    "",
    "Tells platforms what kind of content this is. For most pages, it's 'website'. For articles, use 'article'. For products, use 'product'.",
    "",
    "---",
    "",
    "## How to add OG tags to different platforms",
    "",
    "### WordPress (with Yoast SEO)",
    "",
    "- Install Yoast SEO if you haven't already",
    "- Go to each page/post → Yoast SEO → Social tab",
    "- Set the Social title, description, and image",
    "- Alternatively: go to SEO → Social → Facebook → enable 'Add Open Graph meta data'",
    "",
    "Yoast auto-generates OG tags from your SEO title/description. But you should set a custom OG image for important pages.",
    "",
    "### Shopify",
    "",
    "- Go to Online Store → Preferences → scroll to Social sharing image",
    "- Upload a 1200×630px image for the homepage",
    "- For product pages: go to each product → scroll to 'Search engine listing preview' → edit title + description",
    "- Note: Shopify doesn't have native per-page OG image fields — use a theme that supports it or add to your theme's head template",
    "",
    "### Webflow",
    "",
    "- Open the page settings for each page (gear icon)",
    "- Scroll to 'Open Graph Settings'",
    "- Set title, description, and upload an image",
    "- Publish",
    "",
    "### Next.js (App Router)",
    "",
    "In Next.js 13+ with App Router, use the metadata export in your page.tsx:",
    "",
    "export const metadata = { openGraph: { title: 'Page Title', description: 'Page description', images: [{ url: 'https://yoursite.com/og.jpg', width: 1200, height: 630 }] } }",
    "",
    "---",
    "",
    "## How to test your Open Graph tags",
    "",
    "After adding or updating OG tags, test them before sharing:",
    "",
    "- **Facebook Sharing Debugger**: [developers.facebook.com/tools/debug](https://developers.facebook.com/tools/debug) — paste your URL, see exactly how Facebook will render it. Use 'Scrape Again' to clear the cache.",
    "- **Twitter Card Validator**: [cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)",
    "- **LinkedIn Post Inspector**: [linkedin.com/post-inspector](https://www.linkedin.com/post-inspector/)",
    "- **GetMetaFix** (free): [getmetafix.com](https://getmetafix.com) — checks all OG tags in one audit, tells you what's missing and what's wrong.",
    "",
    "---",
    "",
    "## The most common OG image mistakes",
    "",
    "**1. Relative URLs**",
    "'/images/og.jpg' won't work. Must be 'https://yoursite.com/images/og.jpg'.",
    "",
    "**2. Image doesn't exist**",
    "The URL is set but the file isn't there. Facebook will show nothing.",
    "",
    "**3. Wrong dimensions**",
    "Images smaller than 600×315px may not display. Use 1200×630px for best results across all platforms.",
    "",
    "**4. Same image on every page**",
    "Your homepage's OG image on a blog post looks lazy and confuses people. Use relevant images per page.",
    "",
    "**5. Image has text that gets cut off**",
    "Facebook/LinkedIn crop differently on mobile vs desktop. Keep important text in the centre 80% of the image.",
    "",
    "---",
    "",
    "## Fix your OG tags in 10 minutes",
    "",
    "- Run a free audit at [getmetafix.com](https://getmetafix.com) — see exactly which OG tags are missing",
    "- Create a 1200×630px branded image (Canva has free templates)",
    "- Add the 5 tags above to your HTML head",
    "- Test in Facebook Debugger",
    "- Done",
    "",
    "The $29 fix package at GetMetaFix generates the exact HTML you need, tailored to your page's content.",
  ].join("\n"),
};

export const posts: Post[] = [shopifyPost, ogPost];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
